# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1070, 837)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(5, 10, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_costume_state_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_costume_state_4.sizePolicy().hasHeightForWidth())
        self.label_costume_state_4.setSizePolicy(sizePolicy)
        self.label_costume_state_4.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_costume_state_4.setObjectName("label_costume_state_4")
        self.gridLayout_3.addWidget(self.label_costume_state_4, 4, 4, 1, 1)
        self.label_servant_state_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_servant_state_2.sizePolicy().hasHeightForWidth())
        self.label_servant_state_2.setSizePolicy(sizePolicy)
        self.label_servant_state_2.setMinimumSize(QtCore.QSize(110, 65))
        self.label_servant_state_2.setMaximumSize(QtCore.QSize(16777215, 65))
        self.label_servant_state_2.setObjectName("label_servant_state_2")
        self.gridLayout_3.addWidget(self.label_servant_state_2, 2, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.groupBox)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_3.addWidget(self.line_7, 0, 7, 1, 1)
        self.label_costume_state_1 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_costume_state_1.sizePolicy().hasHeightForWidth())
        self.label_costume_state_1.setSizePolicy(sizePolicy)
        self.label_costume_state_1.setMaximumSize(QtCore.QSize(16777212, 28))
        self.label_costume_state_1.setObjectName("label_costume_state_1")
        self.gridLayout_3.addWidget(self.label_costume_state_1, 4, 0, 1, 1)
        self.box_skill_confirm = QtWidgets.QCheckBox(self.groupBox)
        self.box_skill_confirm.setObjectName("box_skill_confirm")
        self.gridLayout_3.addWidget(self.box_skill_confirm, 4, 8, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.btn_select_servant_5 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_servant_5.sizePolicy().hasHeightForWidth())
        self.btn_select_servant_5.setSizePolicy(sizePolicy)
        self.btn_select_servant_5.setMinimumSize(QtCore.QSize(92, 100))
        self.btn_select_servant_5.setMaximumSize(QtCore.QSize(92, 100))
        self.btn_select_servant_5.setText("")
        self.btn_select_servant_5.setIconSize(QtCore.QSize(92, 100))
        self.btn_select_servant_5.setObjectName("btn_select_servant_5")
        self.horizontalLayout_29.addWidget(self.btn_select_servant_5)
        self.gridLayout_3.addLayout(self.horizontalLayout_29, 0, 5, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinbox_required_prob = QtWidgets.QSpinBox(self.groupBox)
        self.spinbox_required_prob.setMaximum(100)
        self.spinbox_required_prob.setProperty("value", 100)
        self.spinbox_required_prob.setObjectName("spinbox_required_prob")
        self.horizontalLayout_3.addWidget(self.spinbox_required_prob)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 3, 8, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.btn_select_servant_1 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_servant_1.sizePolicy().hasHeightForWidth())
        self.btn_select_servant_1.setSizePolicy(sizePolicy)
        self.btn_select_servant_1.setMinimumSize(QtCore.QSize(92, 100))
        self.btn_select_servant_1.setMaximumSize(QtCore.QSize(92, 100))
        self.btn_select_servant_1.setText("")
        self.btn_select_servant_1.setIconSize(QtCore.QSize(92, 100))
        self.btn_select_servant_1.setObjectName("btn_select_servant_1")
        self.horizontalLayout_24.addWidget(self.btn_select_servant_1)
        self.gridLayout_3.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.label_costume_state_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_costume_state_5.sizePolicy().hasHeightForWidth())
        self.label_costume_state_5.setSizePolicy(sizePolicy)
        self.label_costume_state_5.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_costume_state_5.setObjectName("label_costume_state_5")
        self.gridLayout_3.addWidget(self.label_costume_state_5, 4, 5, 1, 1)
        self.label_costume_state_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_costume_state_6.sizePolicy().hasHeightForWidth())
        self.label_costume_state_6.setSizePolicy(sizePolicy)
        self.label_costume_state_6.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_costume_state_6.setObjectName("label_costume_state_6")
        self.gridLayout_3.addWidget(self.label_costume_state_6, 4, 6, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.btn_select_servant_2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_servant_2.sizePolicy().hasHeightForWidth())
        self.btn_select_servant_2.setSizePolicy(sizePolicy)
        self.btn_select_servant_2.setMinimumSize(QtCore.QSize(92, 100))
        self.btn_select_servant_2.setMaximumSize(QtCore.QSize(92, 100))
        self.btn_select_servant_2.setText("")
        self.btn_select_servant_2.setIconSize(QtCore.QSize(92, 100))
        self.btn_select_servant_2.setObjectName("btn_select_servant_2")
        self.horizontalLayout_26.addWidget(self.btn_select_servant_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_26, 0, 1, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.btn_select_master = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_master.setMinimumSize(QtCore.QSize(92, 100))
        self.btn_select_master.setMaximumSize(QtCore.QSize(92, 100))
        self.btn_select_master.setText("")
        self.btn_select_master.setIconSize(QtCore.QSize(100, 100))
        self.btn_select_master.setObjectName("btn_select_master")
        self.horizontalLayout_23.addWidget(self.btn_select_master)
        self.gridLayout_3.addLayout(self.horizontalLayout_23, 0, 8, 1, 1)
        self.label_servant_state_1 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_servant_state_1.sizePolicy().hasHeightForWidth())
        self.label_servant_state_1.setSizePolicy(sizePolicy)
        self.label_servant_state_1.setMinimumSize(QtCore.QSize(110, 65))
        self.label_servant_state_1.setMaximumSize(QtCore.QSize(16777215, 65))
        self.label_servant_state_1.setObjectName("label_servant_state_1")
        self.gridLayout_3.addWidget(self.label_servant_state_1, 2, 0, 1, 1)
        self.label_master_state = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_master_state.sizePolicy().hasHeightForWidth())
        self.label_master_state.setSizePolicy(sizePolicy)
        self.label_master_state.setMinimumSize(QtCore.QSize(0, 0))
        self.label_master_state.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_master_state.setObjectName("label_master_state")
        self.gridLayout_3.addWidget(self.label_master_state, 2, 8, 1, 1)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.btn_select_costume_3 = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_costume_3.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_select_costume_3.setMaximumSize(QtCore.QSize(100, 45))
        self.btn_select_costume_3.setText("")
        self.btn_select_costume_3.setIconSize(QtCore.QSize(100, 150))
        self.btn_select_costume_3.setObjectName("btn_select_costume_3")
        self.horizontalLayout_38.addWidget(self.btn_select_costume_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_38, 3, 2, 1, 1)
        self.label_costume_state_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_costume_state_2.sizePolicy().hasHeightForWidth())
        self.label_costume_state_2.setSizePolicy(sizePolicy)
        self.label_costume_state_2.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_costume_state_2.setObjectName("label_costume_state_2")
        self.gridLayout_3.addWidget(self.label_costume_state_2, 4, 1, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.btn_select_servant_4 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_servant_4.sizePolicy().hasHeightForWidth())
        self.btn_select_servant_4.setSizePolicy(sizePolicy)
        self.btn_select_servant_4.setMinimumSize(QtCore.QSize(92, 100))
        self.btn_select_servant_4.setMaximumSize(QtCore.QSize(92, 100))
        self.btn_select_servant_4.setText("")
        self.btn_select_servant_4.setIconSize(QtCore.QSize(92, 100))
        self.btn_select_servant_4.setObjectName("btn_select_servant_4")
        self.horizontalLayout_28.addWidget(self.btn_select_servant_4)
        self.gridLayout_3.addLayout(self.horizontalLayout_28, 0, 4, 1, 1)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.btn_select_costume_2 = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_costume_2.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_select_costume_2.setMaximumSize(QtCore.QSize(100, 45))
        self.btn_select_costume_2.setText("")
        self.btn_select_costume_2.setIconSize(QtCore.QSize(100, 150))
        self.btn_select_costume_2.setObjectName("btn_select_costume_2")
        self.horizontalLayout_36.addWidget(self.btn_select_costume_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_36, 3, 1, 1, 1)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.btn_select_costume_1 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_costume_1.sizePolicy().hasHeightForWidth())
        self.btn_select_costume_1.setSizePolicy(sizePolicy)
        self.btn_select_costume_1.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_select_costume_1.setMaximumSize(QtCore.QSize(100, 45))
        self.btn_select_costume_1.setText("")
        self.btn_select_costume_1.setIconSize(QtCore.QSize(100, 150))
        self.btn_select_costume_1.setObjectName("btn_select_costume_1")
        self.horizontalLayout_46.addWidget(self.btn_select_costume_1)
        self.gridLayout_3.addLayout(self.horizontalLayout_46, 3, 0, 1, 1)
        self.label_servant_state_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_servant_state_3.sizePolicy().hasHeightForWidth())
        self.label_servant_state_3.setSizePolicy(sizePolicy)
        self.label_servant_state_3.setMinimumSize(QtCore.QSize(110, 65))
        self.label_servant_state_3.setMaximumSize(QtCore.QSize(16777215, 65))
        self.label_servant_state_3.setObjectName("label_servant_state_3")
        self.gridLayout_3.addWidget(self.label_servant_state_3, 2, 2, 1, 1)
        self.label_servant_state_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_servant_state_5.sizePolicy().hasHeightForWidth())
        self.label_servant_state_5.setSizePolicy(sizePolicy)
        self.label_servant_state_5.setMinimumSize(QtCore.QSize(110, 65))
        self.label_servant_state_5.setMaximumSize(QtCore.QSize(16777215, 65))
        self.label_servant_state_5.setObjectName("label_servant_state_5")
        self.gridLayout_3.addWidget(self.label_servant_state_5, 2, 5, 1, 1)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.btn_select_costume_6 = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_costume_6.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_select_costume_6.setMaximumSize(QtCore.QSize(100, 45))
        self.btn_select_costume_6.setText("")
        self.btn_select_costume_6.setIconSize(QtCore.QSize(100, 150))
        self.btn_select_costume_6.setObjectName("btn_select_costume_6")
        self.horizontalLayout_44.addWidget(self.btn_select_costume_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_44, 3, 6, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.btn_select_servant_3 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_servant_3.sizePolicy().hasHeightForWidth())
        self.btn_select_servant_3.setSizePolicy(sizePolicy)
        self.btn_select_servant_3.setMinimumSize(QtCore.QSize(92, 100))
        self.btn_select_servant_3.setMaximumSize(QtCore.QSize(92, 100))
        self.btn_select_servant_3.setText("")
        self.btn_select_servant_3.setIconSize(QtCore.QSize(92, 100))
        self.btn_select_servant_3.setObjectName("btn_select_servant_3")
        self.horizontalLayout_27.addWidget(self.btn_select_servant_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_27, 0, 2, 1, 1)
        self.label_costume_state_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_costume_state_3.sizePolicy().hasHeightForWidth())
        self.label_costume_state_3.setSizePolicy(sizePolicy)
        self.label_costume_state_3.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_costume_state_3.setObjectName("label_costume_state_3")
        self.gridLayout_3.addWidget(self.label_costume_state_3, 4, 2, 1, 1)
        self.label_servant_state_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_servant_state_4.sizePolicy().hasHeightForWidth())
        self.label_servant_state_4.setSizePolicy(sizePolicy)
        self.label_servant_state_4.setMinimumSize(QtCore.QSize(110, 65))
        self.label_servant_state_4.setMaximumSize(QtCore.QSize(16777215, 65))
        self.label_servant_state_4.setObjectName("label_servant_state_4")
        self.gridLayout_3.addWidget(self.label_servant_state_4, 2, 4, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.groupBox)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_3.addWidget(self.line_8, 3, 7, 1, 1)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.btn_select_costume_4 = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_costume_4.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_select_costume_4.setMaximumSize(QtCore.QSize(100, 45))
        self.btn_select_costume_4.setText("")
        self.btn_select_costume_4.setIconSize(QtCore.QSize(100, 150))
        self.btn_select_costume_4.setObjectName("btn_select_costume_4")
        self.horizontalLayout_40.addWidget(self.btn_select_costume_4)
        self.gridLayout_3.addLayout(self.horizontalLayout_40, 3, 4, 1, 1)
        self.label_servant_state_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_servant_state_6.sizePolicy().hasHeightForWidth())
        self.label_servant_state_6.setSizePolicy(sizePolicy)
        self.label_servant_state_6.setMinimumSize(QtCore.QSize(110, 65))
        self.label_servant_state_6.setMaximumSize(QtCore.QSize(16777215, 65))
        self.label_servant_state_6.setObjectName("label_servant_state_6")
        self.gridLayout_3.addWidget(self.label_servant_state_6, 2, 6, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 0, 3, 1, 1)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.btn_select_costume_5 = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_costume_5.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_select_costume_5.setMaximumSize(QtCore.QSize(100, 45))
        self.btn_select_costume_5.setText("")
        self.btn_select_costume_5.setIconSize(QtCore.QSize(100, 150))
        self.btn_select_costume_5.setObjectName("btn_select_costume_5")
        self.horizontalLayout_42.addWidget(self.btn_select_costume_5)
        self.gridLayout_3.addLayout(self.horizontalLayout_42, 3, 5, 1, 1)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.btn_select_servant_6 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_servant_6.sizePolicy().hasHeightForWidth())
        self.btn_select_servant_6.setSizePolicy(sizePolicy)
        self.btn_select_servant_6.setMinimumSize(QtCore.QSize(92, 100))
        self.btn_select_servant_6.setMaximumSize(QtCore.QSize(92, 100))
        self.btn_select_servant_6.setText("")
        self.btn_select_servant_6.setIconSize(QtCore.QSize(92, 100))
        self.btn_select_servant_6.setObjectName("btn_select_servant_6")
        self.horizontalLayout_30.addWidget(self.btn_select_servant_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_30, 0, 6, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 3, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_set_progress = QtWidgets.QPushButton(self.groupBox)
        self.btn_set_progress.setObjectName("btn_set_progress")
        self.horizontalLayout_4.addWidget(self.btn_set_progress)
        self.btn_choose_level = QtWidgets.QPushButton(self.groupBox)
        self.btn_choose_level.setObjectName("btn_choose_level")
        self.horizontalLayout_4.addWidget(self.btn_choose_level)
        self.btn_confirm_team = QtWidgets.QPushButton(self.groupBox)
        self.btn_confirm_team.setObjectName("btn_confirm_team")
        self.horizontalLayout_4.addWidget(self.btn_confirm_team)
        self.btn_change_team = QtWidgets.QPushButton(self.groupBox)
        self.btn_change_team.setEnabled(False)
        self.btn_change_team.setObjectName("btn_change_team")
        self.horizontalLayout_4.addWidget(self.btn_change_team)
        self.btn_round_reset = QtWidgets.QPushButton(self.groupBox)
        self.btn_round_reset.setEnabled(False)
        self.btn_round_reset.setObjectName("btn_round_reset")
        self.horizontalLayout_4.addWidget(self.btn_round_reset)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.round1_enemy3_class = QtWidgets.QLabel(self.groupBox_2)
        self.round1_enemy3_class.setMinimumSize(QtCore.QSize(150, 0))
        self.round1_enemy3_class.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round1_enemy3_class.setText("")
        self.round1_enemy3_class.setObjectName("round1_enemy3_class")
        self.gridLayout_7.addWidget(self.round1_enemy3_class, 1, 0, 1, 1)
        self.round3_enemy1_class = QtWidgets.QLabel(self.groupBox_2)
        self.round3_enemy1_class.setMinimumSize(QtCore.QSize(150, 0))
        self.round3_enemy1_class.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round3_enemy1_class.setText("")
        self.round3_enemy1_class.setObjectName("round3_enemy1_class")
        self.gridLayout_7.addWidget(self.round3_enemy1_class, 7, 2, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.round2_enemy1_pic = QtWidgets.QPushButton(self.groupBox_2)
        self.round2_enemy1_pic.setEnabled(False)
        self.round2_enemy1_pic.setMinimumSize(QtCore.QSize(64, 64))
        self.round2_enemy1_pic.setMaximumSize(QtCore.QSize(64, 64))
        self.round2_enemy1_pic.setText("")
        self.round2_enemy1_pic.setIconSize(QtCore.QSize(64, 64))
        self.round2_enemy1_pic.setObjectName("round2_enemy1_pic")
        self.horizontalLayout_10.addWidget(self.round2_enemy1_pic)
        self.gridLayout_7.addLayout(self.horizontalLayout_10, 3, 2, 1, 1)
        self.round3_enemy1_health = QtWidgets.QLabel(self.groupBox_2)
        self.round3_enemy1_health.setMinimumSize(QtCore.QSize(150, 0))
        self.round3_enemy1_health.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round3_enemy1_health.setText("")
        self.round3_enemy1_health.setObjectName("round3_enemy1_health")
        self.gridLayout_7.addWidget(self.round3_enemy1_health, 8, 2, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.round3_enemy2_pic = QtWidgets.QPushButton(self.groupBox_2)
        self.round3_enemy2_pic.setEnabled(False)
        self.round3_enemy2_pic.setMinimumSize(QtCore.QSize(64, 64))
        self.round3_enemy2_pic.setMaximumSize(QtCore.QSize(64, 64))
        self.round3_enemy2_pic.setText("")
        self.round3_enemy2_pic.setIconSize(QtCore.QSize(64, 64))
        self.round3_enemy2_pic.setObjectName("round3_enemy2_pic")
        self.horizontalLayout_20.addWidget(self.round3_enemy2_pic)
        self.gridLayout_7.addLayout(self.horizontalLayout_20, 6, 1, 1, 1)
        self.round2_enemy3_class = QtWidgets.QLabel(self.groupBox_2)
        self.round2_enemy3_class.setMinimumSize(QtCore.QSize(150, 0))
        self.round2_enemy3_class.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round2_enemy3_class.setText("")
        self.round2_enemy3_class.setObjectName("round2_enemy3_class")
        self.gridLayout_7.addWidget(self.round2_enemy3_class, 4, 0, 1, 1)
        self.round2_enemy2_class = QtWidgets.QLabel(self.groupBox_2)
        self.round2_enemy2_class.setMinimumSize(QtCore.QSize(150, 0))
        self.round2_enemy2_class.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round2_enemy2_class.setText("")
        self.round2_enemy2_class.setObjectName("round2_enemy2_class")
        self.gridLayout_7.addWidget(self.round2_enemy2_class, 4, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.round2_enemy3_pic = QtWidgets.QPushButton(self.groupBox_2)
        self.round2_enemy3_pic.setEnabled(False)
        self.round2_enemy3_pic.setMinimumSize(QtCore.QSize(64, 64))
        self.round2_enemy3_pic.setMaximumSize(QtCore.QSize(64, 64))
        self.round2_enemy3_pic.setText("")
        self.round2_enemy3_pic.setIconSize(QtCore.QSize(64, 64))
        self.round2_enemy3_pic.setObjectName("round2_enemy3_pic")
        self.horizontalLayout_6.addWidget(self.round2_enemy3_pic)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.round2_enemy2_pic = QtWidgets.QPushButton(self.groupBox_2)
        self.round2_enemy2_pic.setEnabled(False)
        self.round2_enemy2_pic.setMinimumSize(QtCore.QSize(64, 64))
        self.round2_enemy2_pic.setMaximumSize(QtCore.QSize(64, 64))
        self.round2_enemy2_pic.setText("")
        self.round2_enemy2_pic.setIconSize(QtCore.QSize(64, 64))
        self.round2_enemy2_pic.setObjectName("round2_enemy2_pic")
        self.horizontalLayout_7.addWidget(self.round2_enemy2_pic)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 3, 1, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.round3_enemy3_pic = QtWidgets.QPushButton(self.groupBox_2)
        self.round3_enemy3_pic.setEnabled(False)
        self.round3_enemy3_pic.setMinimumSize(QtCore.QSize(64, 64))
        self.round3_enemy3_pic.setMaximumSize(QtCore.QSize(64, 64))
        self.round3_enemy3_pic.setText("")
        self.round3_enemy3_pic.setIconSize(QtCore.QSize(64, 64))
        self.round3_enemy3_pic.setObjectName("round3_enemy3_pic")
        self.horizontalLayout_21.addWidget(self.round3_enemy3_pic)
        self.gridLayout_7.addLayout(self.horizontalLayout_21, 6, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.round1_enemy2_pic = QtWidgets.QPushButton(self.groupBox_2)
        self.round1_enemy2_pic.setEnabled(False)
        self.round1_enemy2_pic.setMinimumSize(QtCore.QSize(64, 64))
        self.round1_enemy2_pic.setMaximumSize(QtCore.QSize(64, 64))
        self.round1_enemy2_pic.setText("")
        self.round1_enemy2_pic.setIconSize(QtCore.QSize(64, 64))
        self.round1_enemy2_pic.setObjectName("round1_enemy2_pic")
        self.horizontalLayout_2.addWidget(self.round1_enemy2_pic)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.round3_enemy3_class = QtWidgets.QLabel(self.groupBox_2)
        self.round3_enemy3_class.setMinimumSize(QtCore.QSize(150, 0))
        self.round3_enemy3_class.setMaximumSize(QtCore.QSize(150, 28))
        self.round3_enemy3_class.setText("")
        self.round3_enemy3_class.setObjectName("round3_enemy3_class")
        self.gridLayout_7.addWidget(self.round3_enemy3_class, 7, 0, 1, 1)
        self.round1_enemy2_class = QtWidgets.QLabel(self.groupBox_2)
        self.round1_enemy2_class.setMinimumSize(QtCore.QSize(150, 0))
        self.round1_enemy2_class.setMaximumSize(QtCore.QSize(150, 28))
        self.round1_enemy2_class.setText("")
        self.round1_enemy2_class.setObjectName("round1_enemy2_class")
        self.gridLayout_7.addWidget(self.round1_enemy2_class, 1, 1, 1, 1)
        self.round3_enemy3_health = QtWidgets.QLabel(self.groupBox_2)
        self.round3_enemy3_health.setMinimumSize(QtCore.QSize(150, 0))
        self.round3_enemy3_health.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round3_enemy3_health.setText("")
        self.round3_enemy3_health.setObjectName("round3_enemy3_health")
        self.gridLayout_7.addWidget(self.round3_enemy3_health, 8, 0, 1, 1)
        self.round1_enemy3_health = QtWidgets.QLabel(self.groupBox_2)
        self.round1_enemy3_health.setMinimumSize(QtCore.QSize(150, 0))
        self.round1_enemy3_health.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round1_enemy3_health.setText("")
        self.round1_enemy3_health.setObjectName("round1_enemy3_health")
        self.gridLayout_7.addWidget(self.round1_enemy3_health, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.round1_enemy1_pic = QtWidgets.QPushButton(self.groupBox_2)
        self.round1_enemy1_pic.setEnabled(False)
        self.round1_enemy1_pic.setMinimumSize(QtCore.QSize(64, 64))
        self.round1_enemy1_pic.setMaximumSize(QtCore.QSize(64, 64))
        self.round1_enemy1_pic.setText("")
        self.round1_enemy1_pic.setIconSize(QtCore.QSize(64, 64))
        self.round1_enemy1_pic.setObjectName("round1_enemy1_pic")
        self.horizontalLayout.addWidget(self.round1_enemy1_pic)
        self.gridLayout_7.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.round2_enemy3_health = QtWidgets.QLabel(self.groupBox_2)
        self.round2_enemy3_health.setMinimumSize(QtCore.QSize(150, 0))
        self.round2_enemy3_health.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round2_enemy3_health.setText("")
        self.round2_enemy3_health.setObjectName("round2_enemy3_health")
        self.gridLayout_7.addWidget(self.round2_enemy3_health, 5, 0, 1, 1)
        self.round2_enemy2_health = QtWidgets.QLabel(self.groupBox_2)
        self.round2_enemy2_health.setMinimumSize(QtCore.QSize(150, 0))
        self.round2_enemy2_health.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round2_enemy2_health.setText("")
        self.round2_enemy2_health.setObjectName("round2_enemy2_health")
        self.gridLayout_7.addWidget(self.round2_enemy2_health, 5, 1, 1, 1)
        self.round3_enemy2_health = QtWidgets.QLabel(self.groupBox_2)
        self.round3_enemy2_health.setMinimumSize(QtCore.QSize(150, 0))
        self.round3_enemy2_health.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round3_enemy2_health.setText("")
        self.round3_enemy2_health.setObjectName("round3_enemy2_health")
        self.gridLayout_7.addWidget(self.round3_enemy2_health, 8, 1, 1, 1)
        self.round1_enemy2_health = QtWidgets.QLabel(self.groupBox_2)
        self.round1_enemy2_health.setMinimumSize(QtCore.QSize(150, 0))
        self.round1_enemy2_health.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round1_enemy2_health.setText("")
        self.round1_enemy2_health.setObjectName("round1_enemy2_health")
        self.gridLayout_7.addWidget(self.round1_enemy2_health, 2, 1, 1, 1)
        self.round2_enemy1_class = QtWidgets.QLabel(self.groupBox_2)
        self.round2_enemy1_class.setMinimumSize(QtCore.QSize(150, 0))
        self.round2_enemy1_class.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round2_enemy1_class.setText("")
        self.round2_enemy1_class.setObjectName("round2_enemy1_class")
        self.gridLayout_7.addWidget(self.round2_enemy1_class, 4, 2, 1, 1)
        self.round1_enemy1_class = QtWidgets.QLabel(self.groupBox_2)
        self.round1_enemy1_class.setMinimumSize(QtCore.QSize(150, 0))
        self.round1_enemy1_class.setMaximumSize(QtCore.QSize(150, 28))
        self.round1_enemy1_class.setText("")
        self.round1_enemy1_class.setObjectName("round1_enemy1_class")
        self.gridLayout_7.addWidget(self.round1_enemy1_class, 1, 2, 1, 1)
        self.round1_enemy1_health = QtWidgets.QLabel(self.groupBox_2)
        self.round1_enemy1_health.setMinimumSize(QtCore.QSize(150, 0))
        self.round1_enemy1_health.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round1_enemy1_health.setText("")
        self.round1_enemy1_health.setObjectName("round1_enemy1_health")
        self.gridLayout_7.addWidget(self.round1_enemy1_health, 2, 2, 1, 1)
        self.round2_enemy1_health = QtWidgets.QLabel(self.groupBox_2)
        self.round2_enemy1_health.setMinimumSize(QtCore.QSize(150, 0))
        self.round2_enemy1_health.setMaximumSize(QtCore.QSize(150, 16777215))
        self.round2_enemy1_health.setText("")
        self.round2_enemy1_health.setObjectName("round2_enemy1_health")
        self.gridLayout_7.addWidget(self.round2_enemy1_health, 5, 2, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.round3_enemy1_pic = QtWidgets.QPushButton(self.groupBox_2)
        self.round3_enemy1_pic.setEnabled(False)
        self.round3_enemy1_pic.setMinimumSize(QtCore.QSize(64, 64))
        self.round3_enemy1_pic.setMaximumSize(QtCore.QSize(64, 64))
        self.round3_enemy1_pic.setText("")
        self.round3_enemy1_pic.setIconSize(QtCore.QSize(64, 64))
        self.round3_enemy1_pic.setObjectName("round3_enemy1_pic")
        self.horizontalLayout_12.addWidget(self.round3_enemy1_pic)
        self.gridLayout_7.addLayout(self.horizontalLayout_12, 6, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.round1_enemy3_pic = QtWidgets.QPushButton(self.groupBox_2)
        self.round1_enemy3_pic.setEnabled(False)
        self.round1_enemy3_pic.setMinimumSize(QtCore.QSize(64, 64))
        self.round1_enemy3_pic.setMaximumSize(QtCore.QSize(64, 64))
        self.round1_enemy3_pic.setText("")
        self.round1_enemy3_pic.setIconSize(QtCore.QSize(64, 64))
        self.round1_enemy3_pic.setObjectName("round1_enemy3_pic")
        self.horizontalLayout_5.addWidget(self.round1_enemy3_pic)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.round3_enemy2_class = QtWidgets.QLabel(self.groupBox_2)
        self.round3_enemy2_class.setMinimumSize(QtCore.QSize(150, 0))
        self.round3_enemy2_class.setMaximumSize(QtCore.QSize(150, 28))
        self.round3_enemy2_class.setText("")
        self.round3_enemy2_class.setObjectName("round3_enemy2_class")
        self.gridLayout_7.addWidget(self.round3_enemy2_class, 7, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_7)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_15.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.round1_label_random = QtWidgets.QLabel(self.groupBox_3)
        self.round1_label_random.setEnabled(False)
        self.round1_label_random.setMaximumSize(QtCore.QSize(100, 16777215))
        self.round1_label_random.setObjectName("round1_label_random")
        self.verticalLayout_5.addWidget(self.round1_label_random)
        self.round1_bar_random = QtWidgets.QSlider(self.groupBox_3)
        self.round1_bar_random.setEnabled(False)
        self.round1_bar_random.setMaximumSize(QtCore.QSize(100, 16777215))
        self.round1_bar_random.setMinimum(90)
        self.round1_bar_random.setMaximum(110)
        self.round1_bar_random.setProperty("value", 90)
        self.round1_bar_random.setOrientation(QtCore.Qt.Horizontal)
        self.round1_bar_random.setObjectName("round1_bar_random")
        self.verticalLayout_5.addWidget(self.round1_bar_random)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 8, 1, 1)
        self.round1_servant2_np = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant2_np.setEnabled(False)
        self.round1_servant2_np.setObjectName("round1_servant2_np")
        self.gridLayout_2.addWidget(self.round1_servant2_np, 4, 5, 1, 1)
        self.round1_servant3_np = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant3_np.setEnabled(False)
        self.round1_servant3_np.setObjectName("round1_servant3_np")
        self.gridLayout_2.addWidget(self.round1_servant3_np, 4, 6, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.round1_servant2_pic = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant2_pic.setEnabled(False)
        self.round1_servant2_pic.setMinimumSize(QtCore.QSize(64, 70))
        self.round1_servant2_pic.setMaximumSize(QtCore.QSize(64, 70))
        self.round1_servant2_pic.setText("")
        self.round1_servant2_pic.setIconSize(QtCore.QSize(64, 70))
        self.round1_servant2_pic.setObjectName("round1_servant2_pic")
        self.horizontalLayout_16.addWidget(self.round1_servant2_pic)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 1, 5, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.round1_servant1_pic = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant1_pic.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.round1_servant1_pic.sizePolicy().hasHeightForWidth())
        self.round1_servant1_pic.setSizePolicy(sizePolicy)
        self.round1_servant1_pic.setMinimumSize(QtCore.QSize(64, 70))
        self.round1_servant1_pic.setMaximumSize(QtCore.QSize(64, 70))
        self.round1_servant1_pic.setText("")
        self.round1_servant1_pic.setIconSize(QtCore.QSize(64, 70))
        self.round1_servant1_pic.setObjectName("round1_servant1_pic")
        self.horizontalLayout_9.addWidget(self.round1_servant1_pic)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 1, 4, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.round1_master_pic = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_master_pic.setEnabled(False)
        self.round1_master_pic.setMinimumSize(QtCore.QSize(64, 70))
        self.round1_master_pic.setMaximumSize(QtCore.QSize(64, 70))
        self.round1_master_pic.setText("")
        self.round1_master_pic.setIconSize(QtCore.QSize(64, 64))
        self.round1_master_pic.setObjectName("round1_master_pic")
        self.horizontalLayout_19.addWidget(self.round1_master_pic)
        self.gridLayout_2.addLayout(self.horizontalLayout_19, 1, 7, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.round1_servant1_skill1 = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant1_skill1.setEnabled(False)
        self.round1_servant1_skill1.setMinimumSize(QtCore.QSize(30, 30))
        self.round1_servant1_skill1.setMaximumSize(QtCore.QSize(30, 30))
        self.round1_servant1_skill1.setText("")
        self.round1_servant1_skill1.setIconSize(QtCore.QSize(30, 30))
        self.round1_servant1_skill1.setObjectName("round1_servant1_skill1")
        self.horizontalLayout_11.addWidget(self.round1_servant1_skill1)
        self.round1_servant1_skill2 = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant1_skill2.setEnabled(False)
        self.round1_servant1_skill2.setMinimumSize(QtCore.QSize(30, 30))
        self.round1_servant1_skill2.setMaximumSize(QtCore.QSize(30, 30))
        self.round1_servant1_skill2.setText("")
        self.round1_servant1_skill2.setIconSize(QtCore.QSize(30, 30))
        self.round1_servant1_skill2.setObjectName("round1_servant1_skill2")
        self.horizontalLayout_11.addWidget(self.round1_servant1_skill2)
        self.round1_servant1_skill3 = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant1_skill3.setEnabled(False)
        self.round1_servant1_skill3.setMinimumSize(QtCore.QSize(30, 30))
        self.round1_servant1_skill3.setMaximumSize(QtCore.QSize(30, 30))
        self.round1_servant1_skill3.setText("")
        self.round1_servant1_skill3.setIconSize(QtCore.QSize(30, 30))
        self.round1_servant1_skill3.setObjectName("round1_servant1_skill3")
        self.horizontalLayout_11.addWidget(self.round1_servant1_skill3)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 3, 4, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.round1_servant3_pic = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant3_pic.setEnabled(False)
        self.round1_servant3_pic.setMinimumSize(QtCore.QSize(64, 70))
        self.round1_servant3_pic.setMaximumSize(QtCore.QSize(64, 70))
        self.round1_servant3_pic.setText("")
        self.round1_servant3_pic.setIconSize(QtCore.QSize(64, 70))
        self.round1_servant3_pic.setObjectName("round1_servant3_pic")
        self.horizontalLayout_17.addWidget(self.round1_servant3_pic)
        self.gridLayout_2.addLayout(self.horizontalLayout_17, 1, 6, 1, 1)
        self.btn_round1_next = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_round1_next.setEnabled(False)
        self.btn_round1_next.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_round1_next.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btn_round1_next.setObjectName("btn_round1_next")
        self.gridLayout_2.addWidget(self.btn_round1_next, 3, 8, 1, 1)
        self.round1_servant1_np = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant1_np.setEnabled(False)
        self.round1_servant1_np.setObjectName("round1_servant1_np")
        self.gridLayout_2.addWidget(self.round1_servant1_np, 4, 4, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.round1_servant3_skill1 = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant3_skill1.setEnabled(False)
        self.round1_servant3_skill1.setMinimumSize(QtCore.QSize(30, 30))
        self.round1_servant3_skill1.setMaximumSize(QtCore.QSize(30, 30))
        self.round1_servant3_skill1.setText("")
        self.round1_servant3_skill1.setIconSize(QtCore.QSize(30, 30))
        self.round1_servant3_skill1.setObjectName("round1_servant3_skill1")
        self.horizontalLayout_14.addWidget(self.round1_servant3_skill1)
        self.round1_servant3_skill2 = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant3_skill2.setEnabled(False)
        self.round1_servant3_skill2.setMinimumSize(QtCore.QSize(30, 30))
        self.round1_servant3_skill2.setMaximumSize(QtCore.QSize(30, 30))
        self.round1_servant3_skill2.setText("")
        self.round1_servant3_skill2.setIconSize(QtCore.QSize(30, 30))
        self.round1_servant3_skill2.setObjectName("round1_servant3_skill2")
        self.horizontalLayout_14.addWidget(self.round1_servant3_skill2)
        self.round1_servant3_skill3 = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant3_skill3.setEnabled(False)
        self.round1_servant3_skill3.setMinimumSize(QtCore.QSize(30, 30))
        self.round1_servant3_skill3.setMaximumSize(QtCore.QSize(30, 30))
        self.round1_servant3_skill3.setText("")
        self.round1_servant3_skill3.setIconSize(QtCore.QSize(30, 30))
        self.round1_servant3_skill3.setObjectName("round1_servant3_skill3")
        self.horizontalLayout_14.addWidget(self.round1_servant3_skill3)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 3, 6, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.round1_master_skill1 = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_master_skill1.setEnabled(False)
        self.round1_master_skill1.setMinimumSize(QtCore.QSize(30, 30))
        self.round1_master_skill1.setMaximumSize(QtCore.QSize(30, 30))
        self.round1_master_skill1.setText("")
        self.round1_master_skill1.setIconSize(QtCore.QSize(30, 30))
        self.round1_master_skill1.setObjectName("round1_master_skill1")
        self.horizontalLayout_18.addWidget(self.round1_master_skill1)
        self.round1_master_skill2 = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_master_skill2.setEnabled(False)
        self.round1_master_skill2.setMinimumSize(QtCore.QSize(30, 30))
        self.round1_master_skill2.setMaximumSize(QtCore.QSize(30, 30))
        self.round1_master_skill2.setText("")
        self.round1_master_skill2.setIconSize(QtCore.QSize(30, 30))
        self.round1_master_skill2.setObjectName("round1_master_skill2")
        self.horizontalLayout_18.addWidget(self.round1_master_skill2)
        self.round1_master_skill3 = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_master_skill3.setEnabled(False)
        self.round1_master_skill3.setMinimumSize(QtCore.QSize(30, 30))
        self.round1_master_skill3.setMaximumSize(QtCore.QSize(30, 30))
        self.round1_master_skill3.setText("")
        self.round1_master_skill3.setIconSize(QtCore.QSize(30, 30))
        self.round1_master_skill3.setObjectName("round1_master_skill3")
        self.horizontalLayout_18.addWidget(self.round1_master_skill3)
        self.gridLayout_2.addLayout(self.horizontalLayout_18, 3, 7, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.round1_servant2_skill1 = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant2_skill1.setEnabled(False)
        self.round1_servant2_skill1.setMinimumSize(QtCore.QSize(30, 30))
        self.round1_servant2_skill1.setMaximumSize(QtCore.QSize(30, 30))
        self.round1_servant2_skill1.setText("")
        self.round1_servant2_skill1.setIconSize(QtCore.QSize(30, 30))
        self.round1_servant2_skill1.setObjectName("round1_servant2_skill1")
        self.horizontalLayout_13.addWidget(self.round1_servant2_skill1)
        self.round1_servant2_skill2 = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant2_skill2.setEnabled(False)
        self.round1_servant2_skill2.setMinimumSize(QtCore.QSize(30, 30))
        self.round1_servant2_skill2.setMaximumSize(QtCore.QSize(30, 30))
        self.round1_servant2_skill2.setText("")
        self.round1_servant2_skill2.setIconSize(QtCore.QSize(30, 30))
        self.round1_servant2_skill2.setObjectName("round1_servant2_skill2")
        self.horizontalLayout_13.addWidget(self.round1_servant2_skill2)
        self.round1_servant2_skill3 = QtWidgets.QPushButton(self.groupBox_3)
        self.round1_servant2_skill3.setEnabled(False)
        self.round1_servant2_skill3.setMinimumSize(QtCore.QSize(30, 30))
        self.round1_servant2_skill3.setMaximumSize(QtCore.QSize(30, 30))
        self.round1_servant2_skill3.setText("")
        self.round1_servant2_skill3.setIconSize(QtCore.QSize(30, 30))
        self.round1_servant2_skill3.setObjectName("round1_servant2_skill3")
        self.horizontalLayout_13.addWidget(self.round1_servant2_skill3)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 3, 5, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.round2_servant3_np = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant3_np.setEnabled(False)
        self.round2_servant3_np.setObjectName("round2_servant3_np")
        self.gridLayout_4.addWidget(self.round2_servant3_np, 3, 5, 1, 1)
        self.horizontalLayout_181 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_181.setObjectName("horizontalLayout_181")
        self.round2_master_skill1 = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_master_skill1.setEnabled(False)
        self.round2_master_skill1.setMinimumSize(QtCore.QSize(30, 30))
        self.round2_master_skill1.setMaximumSize(QtCore.QSize(30, 30))
        self.round2_master_skill1.setText("")
        self.round2_master_skill1.setIconSize(QtCore.QSize(30, 30))
        self.round2_master_skill1.setObjectName("round2_master_skill1")
        self.horizontalLayout_181.addWidget(self.round2_master_skill1)
        self.round2_master_skill2 = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_master_skill2.setEnabled(False)
        self.round2_master_skill2.setMinimumSize(QtCore.QSize(30, 30))
        self.round2_master_skill2.setMaximumSize(QtCore.QSize(30, 30))
        self.round2_master_skill2.setText("")
        self.round2_master_skill2.setIconSize(QtCore.QSize(30, 30))
        self.round2_master_skill2.setObjectName("round2_master_skill2")
        self.horizontalLayout_181.addWidget(self.round2_master_skill2)
        self.round2_master_skill3 = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_master_skill3.setEnabled(False)
        self.round2_master_skill3.setMinimumSize(QtCore.QSize(30, 30))
        self.round2_master_skill3.setMaximumSize(QtCore.QSize(30, 30))
        self.round2_master_skill3.setText("")
        self.round2_master_skill3.setIconSize(QtCore.QSize(30, 30))
        self.round2_master_skill3.setObjectName("round2_master_skill3")
        self.horizontalLayout_181.addWidget(self.round2_master_skill3)
        self.gridLayout_4.addLayout(self.horizontalLayout_181, 1, 6, 1, 1)
        self.round2_servant1_np = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant1_np.setEnabled(False)
        self.round2_servant1_np.setObjectName("round2_servant1_np")
        self.gridLayout_4.addWidget(self.round2_servant1_np, 3, 3, 1, 1)
        self.horizontalLayout_171 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_171.setObjectName("horizontalLayout_171")
        self.round2_servant3_pic = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant3_pic.setEnabled(False)
        self.round2_servant3_pic.setMinimumSize(QtCore.QSize(64, 70))
        self.round2_servant3_pic.setMaximumSize(QtCore.QSize(64, 70))
        self.round2_servant3_pic.setText("")
        self.round2_servant3_pic.setIconSize(QtCore.QSize(64, 70))
        self.round2_servant3_pic.setObjectName("round2_servant3_pic")
        self.horizontalLayout_171.addWidget(self.round2_servant3_pic)
        self.gridLayout_4.addLayout(self.horizontalLayout_171, 0, 5, 1, 1)
        self.horizontalLayout_161 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_161.setObjectName("horizontalLayout_161")
        self.round2_servant2_pic = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant2_pic.setEnabled(False)
        self.round2_servant2_pic.setMinimumSize(QtCore.QSize(64, 70))
        self.round2_servant2_pic.setMaximumSize(QtCore.QSize(64, 70))
        self.round2_servant2_pic.setText("")
        self.round2_servant2_pic.setIconSize(QtCore.QSize(64, 70))
        self.round2_servant2_pic.setObjectName("round2_servant2_pic")
        self.horizontalLayout_161.addWidget(self.round2_servant2_pic)
        self.gridLayout_4.addLayout(self.horizontalLayout_161, 0, 4, 1, 1)
        self.horizontalLayout_131 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_131.setObjectName("horizontalLayout_131")
        self.round2_servant2_skill1 = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant2_skill1.setEnabled(False)
        self.round2_servant2_skill1.setMinimumSize(QtCore.QSize(30, 30))
        self.round2_servant2_skill1.setMaximumSize(QtCore.QSize(30, 30))
        self.round2_servant2_skill1.setText("")
        self.round2_servant2_skill1.setIconSize(QtCore.QSize(30, 30))
        self.round2_servant2_skill1.setObjectName("round2_servant2_skill1")
        self.horizontalLayout_131.addWidget(self.round2_servant2_skill1)
        self.round2_servant2_skill2 = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant2_skill2.setEnabled(False)
        self.round2_servant2_skill2.setMinimumSize(QtCore.QSize(30, 30))
        self.round2_servant2_skill2.setMaximumSize(QtCore.QSize(30, 30))
        self.round2_servant2_skill2.setText("")
        self.round2_servant2_skill2.setIconSize(QtCore.QSize(30, 30))
        self.round2_servant2_skill2.setObjectName("round2_servant2_skill2")
        self.horizontalLayout_131.addWidget(self.round2_servant2_skill2)
        self.round2_servant2_skill3 = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant2_skill3.setEnabled(False)
        self.round2_servant2_skill3.setMinimumSize(QtCore.QSize(30, 30))
        self.round2_servant2_skill3.setMaximumSize(QtCore.QSize(30, 30))
        self.round2_servant2_skill3.setText("")
        self.round2_servant2_skill3.setIconSize(QtCore.QSize(30, 30))
        self.round2_servant2_skill3.setObjectName("round2_servant2_skill3")
        self.horizontalLayout_131.addWidget(self.round2_servant2_skill3)
        self.gridLayout_4.addLayout(self.horizontalLayout_131, 1, 4, 1, 1)
        self.horizontalLayout_141 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_141.setObjectName("horizontalLayout_141")
        self.round2_servant3_skill1 = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant3_skill1.setEnabled(False)
        self.round2_servant3_skill1.setMinimumSize(QtCore.QSize(30, 30))
        self.round2_servant3_skill1.setMaximumSize(QtCore.QSize(30, 30))
        self.round2_servant3_skill1.setText("")
        self.round2_servant3_skill1.setIconSize(QtCore.QSize(30, 30))
        self.round2_servant3_skill1.setObjectName("round2_servant3_skill1")
        self.horizontalLayout_141.addWidget(self.round2_servant3_skill1)
        self.round2_servant3_skill2 = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant3_skill2.setEnabled(False)
        self.round2_servant3_skill2.setMinimumSize(QtCore.QSize(30, 30))
        self.round2_servant3_skill2.setMaximumSize(QtCore.QSize(30, 30))
        self.round2_servant3_skill2.setText("")
        self.round2_servant3_skill2.setIconSize(QtCore.QSize(30, 30))
        self.round2_servant3_skill2.setObjectName("round2_servant3_skill2")
        self.horizontalLayout_141.addWidget(self.round2_servant3_skill2)
        self.round2_servant3_skill3 = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant3_skill3.setEnabled(False)
        self.round2_servant3_skill3.setMinimumSize(QtCore.QSize(30, 30))
        self.round2_servant3_skill3.setMaximumSize(QtCore.QSize(30, 30))
        self.round2_servant3_skill3.setText("")
        self.round2_servant3_skill3.setIconSize(QtCore.QSize(30, 30))
        self.round2_servant3_skill3.setObjectName("round2_servant3_skill3")
        self.horizontalLayout_141.addWidget(self.round2_servant3_skill3)
        self.gridLayout_4.addLayout(self.horizontalLayout_141, 1, 5, 1, 1)
        self.btn_round2_next = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_round2_next.setEnabled(False)
        self.btn_round2_next.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_round2_next.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_round2_next.setObjectName("btn_round2_next")
        self.gridLayout_4.addWidget(self.btn_round2_next, 1, 7, 1, 1)
        self.horizontalLayout_191 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_191.setObjectName("horizontalLayout_191")
        self.round2_master_pic = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_master_pic.setEnabled(False)
        self.round2_master_pic.setMinimumSize(QtCore.QSize(64, 70))
        self.round2_master_pic.setMaximumSize(QtCore.QSize(64, 70))
        self.round2_master_pic.setText("")
        self.round2_master_pic.setIconSize(QtCore.QSize(64, 64))
        self.round2_master_pic.setObjectName("round2_master_pic")
        self.horizontalLayout_191.addWidget(self.round2_master_pic)
        self.gridLayout_4.addLayout(self.horizontalLayout_191, 0, 6, 1, 1)
        self.round2_servant2_np = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant2_np.setEnabled(False)
        self.round2_servant2_np.setObjectName("round2_servant2_np")
        self.gridLayout_4.addWidget(self.round2_servant2_np, 3, 4, 1, 1)
        self.horizontalLayout_91 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_91.setObjectName("horizontalLayout_91")
        self.round2_servant1_pic = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant1_pic.setEnabled(False)
        self.round2_servant1_pic.setMinimumSize(QtCore.QSize(64, 70))
        self.round2_servant1_pic.setMaximumSize(QtCore.QSize(64, 70))
        self.round2_servant1_pic.setText("")
        self.round2_servant1_pic.setIconSize(QtCore.QSize(64, 70))
        self.round2_servant1_pic.setObjectName("round2_servant1_pic")
        self.horizontalLayout_91.addWidget(self.round2_servant1_pic)
        self.gridLayout_4.addLayout(self.horizontalLayout_91, 0, 3, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.round2_label_random = QtWidgets.QLabel(self.groupBox_3)
        self.round2_label_random.setEnabled(False)
        self.round2_label_random.setObjectName("round2_label_random")
        self.verticalLayout_12.addWidget(self.round2_label_random)
        self.round2_bar_random = QtWidgets.QSlider(self.groupBox_3)
        self.round2_bar_random.setEnabled(False)
        self.round2_bar_random.setMaximumSize(QtCore.QSize(100, 16777215))
        self.round2_bar_random.setMinimum(90)
        self.round2_bar_random.setMaximum(110)
        self.round2_bar_random.setProperty("value", 90)
        self.round2_bar_random.setOrientation(QtCore.Qt.Horizontal)
        self.round2_bar_random.setObjectName("round2_bar_random")
        self.verticalLayout_12.addWidget(self.round2_bar_random)
        self.gridLayout_4.addLayout(self.verticalLayout_12, 0, 7, 1, 1)
        self.horizontalLayout_111 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_111.setObjectName("horizontalLayout_111")
        self.round2_servant1_skill1 = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant1_skill1.setEnabled(False)
        self.round2_servant1_skill1.setMinimumSize(QtCore.QSize(30, 30))
        self.round2_servant1_skill1.setMaximumSize(QtCore.QSize(30, 30))
        self.round2_servant1_skill1.setText("")
        self.round2_servant1_skill1.setIconSize(QtCore.QSize(30, 30))
        self.round2_servant1_skill1.setObjectName("round2_servant1_skill1")
        self.horizontalLayout_111.addWidget(self.round2_servant1_skill1)
        self.round2_servant1_skill2 = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant1_skill2.setEnabled(False)
        self.round2_servant1_skill2.setMinimumSize(QtCore.QSize(30, 30))
        self.round2_servant1_skill2.setMaximumSize(QtCore.QSize(30, 30))
        self.round2_servant1_skill2.setText("")
        self.round2_servant1_skill2.setIconSize(QtCore.QSize(30, 30))
        self.round2_servant1_skill2.setObjectName("round2_servant1_skill2")
        self.horizontalLayout_111.addWidget(self.round2_servant1_skill2)
        self.round2_servant1_skill3 = QtWidgets.QPushButton(self.groupBox_3)
        self.round2_servant1_skill3.setEnabled(False)
        self.round2_servant1_skill3.setMinimumSize(QtCore.QSize(30, 30))
        self.round2_servant1_skill3.setMaximumSize(QtCore.QSize(30, 30))
        self.round2_servant1_skill3.setText("")
        self.round2_servant1_skill3.setIconSize(QtCore.QSize(30, 30))
        self.round2_servant1_skill3.setObjectName("round2_servant1_skill3")
        self.horizontalLayout_111.addWidget(self.round2_servant1_skill3)
        self.gridLayout_4.addLayout(self.horizontalLayout_111, 1, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.round3_servant3_np = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant3_np.setEnabled(False)
        self.round3_servant3_np.setObjectName("round3_servant3_np")
        self.gridLayout_5.addWidget(self.round3_servant3_np, 3, 6, 1, 1)
        self.horizontalLayout_192 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_192.setObjectName("horizontalLayout_192")
        self.round3_master_pic = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_master_pic.setEnabled(False)
        self.round3_master_pic.setMinimumSize(QtCore.QSize(64, 70))
        self.round3_master_pic.setMaximumSize(QtCore.QSize(64, 70))
        self.round3_master_pic.setText("")
        self.round3_master_pic.setIconSize(QtCore.QSize(64, 64))
        self.round3_master_pic.setObjectName("round3_master_pic")
        self.horizontalLayout_192.addWidget(self.round3_master_pic)
        self.gridLayout_5.addLayout(self.horizontalLayout_192, 0, 7, 1, 1)
        self.horizontalLayout_92 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_92.setObjectName("horizontalLayout_92")
        self.round3_servant1_pic = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant1_pic.setEnabled(False)
        self.round3_servant1_pic.setMinimumSize(QtCore.QSize(64, 70))
        self.round3_servant1_pic.setMaximumSize(QtCore.QSize(64, 70))
        self.round3_servant1_pic.setText("")
        self.round3_servant1_pic.setIconSize(QtCore.QSize(64, 70))
        self.round3_servant1_pic.setObjectName("round3_servant1_pic")
        self.horizontalLayout_92.addWidget(self.round3_servant1_pic)
        self.gridLayout_5.addLayout(self.horizontalLayout_92, 0, 3, 1, 1)
        self.round3_servant1_np = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant1_np.setEnabled(False)
        self.round3_servant1_np.setObjectName("round3_servant1_np")
        self.gridLayout_5.addWidget(self.round3_servant1_np, 3, 3, 1, 1)
        self.round3_servant2_np = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant2_np.setEnabled(False)
        self.round3_servant2_np.setObjectName("round3_servant2_np")
        self.gridLayout_5.addWidget(self.round3_servant2_np, 3, 5, 1, 1)
        self.horizontalLayout_172 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_172.setObjectName("horizontalLayout_172")
        self.round3_servant3_pic = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant3_pic.setEnabled(False)
        self.round3_servant3_pic.setMinimumSize(QtCore.QSize(64, 70))
        self.round3_servant3_pic.setMaximumSize(QtCore.QSize(64, 70))
        self.round3_servant3_pic.setText("")
        self.round3_servant3_pic.setIconSize(QtCore.QSize(64, 70))
        self.round3_servant3_pic.setObjectName("round3_servant3_pic")
        self.horizontalLayout_172.addWidget(self.round3_servant3_pic)
        self.gridLayout_5.addLayout(self.horizontalLayout_172, 0, 6, 1, 1)
        self.horizontalLayout_162 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_162.setObjectName("horizontalLayout_162")
        self.round3_servant2_pic = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant2_pic.setEnabled(False)
        self.round3_servant2_pic.setMinimumSize(QtCore.QSize(64, 70))
        self.round3_servant2_pic.setMaximumSize(QtCore.QSize(64, 70))
        self.round3_servant2_pic.setText("")
        self.round3_servant2_pic.setIconSize(QtCore.QSize(64, 70))
        self.round3_servant2_pic.setObjectName("round3_servant2_pic")
        self.horizontalLayout_162.addWidget(self.round3_servant2_pic)
        self.gridLayout_5.addLayout(self.horizontalLayout_162, 0, 5, 1, 1)
        self.btn_output_strategy = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_output_strategy.setEnabled(False)
        self.btn_output_strategy.setObjectName("btn_output_strategy")
        self.gridLayout_5.addWidget(self.btn_output_strategy, 2, 9, 1, 1)
        self.horizontalLayout_132 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_132.setObjectName("horizontalLayout_132")
        self.round3_servant2_skill1 = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant2_skill1.setEnabled(False)
        self.round3_servant2_skill1.setMinimumSize(QtCore.QSize(30, 30))
        self.round3_servant2_skill1.setMaximumSize(QtCore.QSize(30, 30))
        self.round3_servant2_skill1.setText("")
        self.round3_servant2_skill1.setIconSize(QtCore.QSize(30, 30))
        self.round3_servant2_skill1.setObjectName("round3_servant2_skill1")
        self.horizontalLayout_132.addWidget(self.round3_servant2_skill1)
        self.round3_servant2_skill2 = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant2_skill2.setEnabled(False)
        self.round3_servant2_skill2.setMinimumSize(QtCore.QSize(30, 30))
        self.round3_servant2_skill2.setMaximumSize(QtCore.QSize(30, 30))
        self.round3_servant2_skill2.setText("")
        self.round3_servant2_skill2.setIconSize(QtCore.QSize(30, 30))
        self.round3_servant2_skill2.setObjectName("round3_servant2_skill2")
        self.horizontalLayout_132.addWidget(self.round3_servant2_skill2)
        self.round3_servant2_skill3 = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant2_skill3.setEnabled(False)
        self.round3_servant2_skill3.setMinimumSize(QtCore.QSize(30, 30))
        self.round3_servant2_skill3.setMaximumSize(QtCore.QSize(30, 30))
        self.round3_servant2_skill3.setText("")
        self.round3_servant2_skill3.setIconSize(QtCore.QSize(30, 30))
        self.round3_servant2_skill3.setObjectName("round3_servant2_skill3")
        self.horizontalLayout_132.addWidget(self.round3_servant2_skill3)
        self.gridLayout_5.addLayout(self.horizontalLayout_132, 2, 5, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.round3_label_random = QtWidgets.QLabel(self.groupBox_3)
        self.round3_label_random.setEnabled(False)
        self.round3_label_random.setObjectName("round3_label_random")
        self.verticalLayout_13.addWidget(self.round3_label_random)
        self.round3_bar_random = QtWidgets.QSlider(self.groupBox_3)
        self.round3_bar_random.setEnabled(False)
        self.round3_bar_random.setMaximumSize(QtCore.QSize(100, 16777215))
        self.round3_bar_random.setMinimum(90)
        self.round3_bar_random.setMaximum(110)
        self.round3_bar_random.setProperty("value", 90)
        self.round3_bar_random.setOrientation(QtCore.Qt.Horizontal)
        self.round3_bar_random.setObjectName("round3_bar_random")
        self.verticalLayout_13.addWidget(self.round3_bar_random)
        self.gridLayout_5.addLayout(self.verticalLayout_13, 0, 9, 1, 1)
        self.horizontalLayout_182 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_182.setObjectName("horizontalLayout_182")
        self.round3_master_skill1 = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_master_skill1.setEnabled(False)
        self.round3_master_skill1.setMinimumSize(QtCore.QSize(30, 30))
        self.round3_master_skill1.setMaximumSize(QtCore.QSize(30, 30))
        self.round3_master_skill1.setText("")
        self.round3_master_skill1.setIconSize(QtCore.QSize(30, 30))
        self.round3_master_skill1.setObjectName("round3_master_skill1")
        self.horizontalLayout_182.addWidget(self.round3_master_skill1)
        self.round3_master_skill2 = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_master_skill2.setEnabled(False)
        self.round3_master_skill2.setMinimumSize(QtCore.QSize(30, 30))
        self.round3_master_skill2.setMaximumSize(QtCore.QSize(30, 30))
        self.round3_master_skill2.setText("")
        self.round3_master_skill2.setIconSize(QtCore.QSize(30, 30))
        self.round3_master_skill2.setObjectName("round3_master_skill2")
        self.horizontalLayout_182.addWidget(self.round3_master_skill2)
        self.round3_master_skill3 = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_master_skill3.setEnabled(False)
        self.round3_master_skill3.setMinimumSize(QtCore.QSize(30, 30))
        self.round3_master_skill3.setMaximumSize(QtCore.QSize(30, 30))
        self.round3_master_skill3.setText("")
        self.round3_master_skill3.setIconSize(QtCore.QSize(30, 30))
        self.round3_master_skill3.setObjectName("round3_master_skill3")
        self.horizontalLayout_182.addWidget(self.round3_master_skill3)
        self.gridLayout_5.addLayout(self.horizontalLayout_182, 2, 7, 1, 1)
        self.horizontalLayout_142 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_142.setObjectName("horizontalLayout_142")
        self.round3_servant3_skill1 = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant3_skill1.setEnabled(False)
        self.round3_servant3_skill1.setMinimumSize(QtCore.QSize(30, 30))
        self.round3_servant3_skill1.setMaximumSize(QtCore.QSize(30, 30))
        self.round3_servant3_skill1.setText("")
        self.round3_servant3_skill1.setIconSize(QtCore.QSize(30, 30))
        self.round3_servant3_skill1.setObjectName("round3_servant3_skill1")
        self.horizontalLayout_142.addWidget(self.round3_servant3_skill1)
        self.round3_servant3_skill2 = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant3_skill2.setEnabled(False)
        self.round3_servant3_skill2.setMinimumSize(QtCore.QSize(30, 30))
        self.round3_servant3_skill2.setMaximumSize(QtCore.QSize(30, 30))
        self.round3_servant3_skill2.setText("")
        self.round3_servant3_skill2.setIconSize(QtCore.QSize(30, 30))
        self.round3_servant3_skill2.setObjectName("round3_servant3_skill2")
        self.horizontalLayout_142.addWidget(self.round3_servant3_skill2)
        self.round3_servant3_skill3 = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant3_skill3.setEnabled(False)
        self.round3_servant3_skill3.setMinimumSize(QtCore.QSize(30, 30))
        self.round3_servant3_skill3.setMaximumSize(QtCore.QSize(30, 30))
        self.round3_servant3_skill3.setText("")
        self.round3_servant3_skill3.setIconSize(QtCore.QSize(30, 30))
        self.round3_servant3_skill3.setObjectName("round3_servant3_skill3")
        self.horizontalLayout_142.addWidget(self.round3_servant3_skill3)
        self.gridLayout_5.addLayout(self.horizontalLayout_142, 2, 6, 1, 1)
        self.horizontalLayout_112 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_112.setObjectName("horizontalLayout_112")
        self.round3_servant1_skill1 = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant1_skill1.setEnabled(False)
        self.round3_servant1_skill1.setMinimumSize(QtCore.QSize(30, 30))
        self.round3_servant1_skill1.setMaximumSize(QtCore.QSize(30, 30))
        self.round3_servant1_skill1.setText("")
        self.round3_servant1_skill1.setIconSize(QtCore.QSize(30, 30))
        self.round3_servant1_skill1.setObjectName("round3_servant1_skill1")
        self.horizontalLayout_112.addWidget(self.round3_servant1_skill1)
        self.round3_servant1_skill2 = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant1_skill2.setEnabled(False)
        self.round3_servant1_skill2.setMinimumSize(QtCore.QSize(30, 30))
        self.round3_servant1_skill2.setMaximumSize(QtCore.QSize(30, 30))
        self.round3_servant1_skill2.setText("")
        self.round3_servant1_skill2.setIconSize(QtCore.QSize(30, 30))
        self.round3_servant1_skill2.setObjectName("round3_servant1_skill2")
        self.horizontalLayout_112.addWidget(self.round3_servant1_skill2)
        self.round3_servant1_skill3 = QtWidgets.QPushButton(self.groupBox_3)
        self.round3_servant1_skill3.setEnabled(False)
        self.round3_servant1_skill3.setMinimumSize(QtCore.QSize(30, 30))
        self.round3_servant1_skill3.setMaximumSize(QtCore.QSize(30, 30))
        self.round3_servant1_skill3.setText("")
        self.round3_servant1_skill3.setIconSize(QtCore.QSize(30, 30))
        self.round3_servant1_skill3.setObjectName("round3_servant1_skill3")
        self.horizontalLayout_112.addWidget(self.round3_servant1_skill3)
        self.gridLayout_5.addLayout(self.horizontalLayout_112, 2, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_5)
        self.horizontalLayout_15.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_update = QtWidgets.QAction(MainWindow)
        self.action_update.setObjectName("action_update")
        self.action_mooncell = QtWidgets.QAction(MainWindow)
        self.action_mooncell.setObjectName("action_mooncell")
        self.action_support = QtWidgets.QAction(MainWindow)
        self.action_support.setObjectName("action_support")
        self.action_kazemai = QtWidgets.QAction(MainWindow)
        self.action_kazemai.setObjectName("action_kazemai")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.menu.addAction(self.action_update)
        self.menu.addAction(self.action_support)
        self.menu.addAction(self.action_about)
        self.menu.addSeparator()
        self.menu.addAction(self.action_mooncell)
        self.menu.addAction(self.action_kazemai)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FGO周回组队器"))
        self.label_costume_state_4.setText(_translate("MainWindow", "等级: "))
        self.label_servant_state_2.setText(_translate("MainWindow", "技能: \n"
"宝具: \n"
"等级: \n"
"芙芙:"))
        self.label_costume_state_1.setText(_translate("MainWindow", "等级: "))
        self.box_skill_confirm.setText(_translate("MainWindow", "技能提示"))
        self.label.setText(_translate("MainWindow", "概率阈值:"))
        self.label_costume_state_5.setText(_translate("MainWindow", "等级: "))
        self.label_costume_state_6.setText(_translate("MainWindow", "等级: "))
        self.label_servant_state_1.setText(_translate("MainWindow", "技能: \n"
"宝具: \n"
"等级: \n"
"芙芙:"))
        self.label_master_state.setText(_translate("MainWindow", "等级:"))
        self.label_costume_state_2.setText(_translate("MainWindow", "等级: "))
        self.label_servant_state_3.setText(_translate("MainWindow", "技能: \n"
"宝具: \n"
"等级: \n"
"芙芙:"))
        self.label_servant_state_5.setText(_translate("MainWindow", "技能: \n"
"宝具: \n"
"等级: \n"
"芙芙:"))
        self.label_costume_state_3.setText(_translate("MainWindow", "等级: "))
        self.label_servant_state_4.setText(_translate("MainWindow", "技能: \n"
"宝具: \n"
"等级: \n"
"芙芙:"))
        self.label_servant_state_6.setText(_translate("MainWindow", "技能: \n"
"宝具: \n"
"等级: \n"
"芙芙:"))
        self.btn_set_progress.setText(_translate("MainWindow", "选择进度"))
        self.btn_choose_level.setText(_translate("MainWindow", "设置副本"))
        self.btn_confirm_team.setText(_translate("MainWindow", "确  认"))
        self.btn_change_team.setText(_translate("MainWindow", "修  改"))
        self.btn_round_reset.setText(_translate("MainWindow", "撤  销"))
        self.round1_label_random.setText(_translate("MainWindow", "随机数: 0.9"))
        self.round1_servant2_np.setText(_translate("MainWindow", "宝具: 0%"))
        self.round1_servant3_np.setText(_translate("MainWindow", "宝具: 0%"))
        self.btn_round1_next.setText(_translate("MainWindow", "下一回合"))
        self.round1_servant1_np.setText(_translate("MainWindow", "宝具: 0%"))
        self.round2_servant3_np.setText(_translate("MainWindow", "宝具: 0%"))
        self.round2_servant1_np.setText(_translate("MainWindow", "宝具: 0%"))
        self.btn_round2_next.setText(_translate("MainWindow", "下一回合"))
        self.round2_servant2_np.setText(_translate("MainWindow", "宝具: 0%"))
        self.round2_label_random.setText(_translate("MainWindow", "随机数: 0.9"))
        self.round3_servant3_np.setText(_translate("MainWindow", "宝具: 0%"))
        self.round3_servant1_np.setText(_translate("MainWindow", "宝具: 0%"))
        self.round3_servant2_np.setText(_translate("MainWindow", "宝具: 0%"))
        self.btn_output_strategy.setText(_translate("MainWindow", "输出操作"))
        self.round3_label_random.setText(_translate("MainWindow", "随机数: 0.9"))
        self.menu.setTitle(_translate("MainWindow", "选  项"))
        self.action_update.setText(_translate("MainWindow", "数据库更新"))
        self.action_mooncell.setText(_translate("MainWindow", "Mooncell"))
        self.action_support.setText(_translate("MainWindow", "软件更新"))
        self.action_kazemai.setText(_translate("MainWindow", "茹西教王的理想乡"))
        self.action_about.setText(_translate("MainWindow", "关于软件"))
