# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectTargetUi_Change.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(731, 281)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_1 = QtWidgets.QPushButton(Dialog)
        self.btn_1.setMinimumSize(QtCore.QSize(110, 120))
        self.btn_1.setMaximumSize(QtCore.QSize(110, 120))
        self.btn_1.setText("")
        self.btn_1.setIconSize(QtCore.QSize(120, 120))
        self.btn_1.setObjectName("btn_1")
        self.gridLayout_2.addWidget(self.btn_1, 1, 0, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(Dialog)
        self.btn_5.setMinimumSize(QtCore.QSize(110, 120))
        self.btn_5.setMaximumSize(QtCore.QSize(110, 120))
        self.btn_5.setText("")
        self.btn_5.setIconSize(QtCore.QSize(110, 120))
        self.btn_5.setObjectName("btn_5")
        self.gridLayout_2.addWidget(self.btn_5, 1, 5, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(Dialog)
        self.btn_6.setMinimumSize(QtCore.QSize(110, 120))
        self.btn_6.setMaximumSize(QtCore.QSize(110, 120))
        self.btn_6.setText("")
        self.btn_6.setIconSize(QtCore.QSize(110, 120))
        self.btn_6.setObjectName("btn_6")
        self.gridLayout_2.addWidget(self.btn_6, 1, 6, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(Dialog)
        self.btn_3.setMinimumSize(QtCore.QSize(110, 120))
        self.btn_3.setMaximumSize(QtCore.QSize(110, 120))
        self.btn_3.setText("")
        self.btn_3.setIconSize(QtCore.QSize(120, 120))
        self.btn_3.setObjectName("btn_3")
        self.gridLayout_2.addWidget(self.btn_3, 1, 2, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(Dialog)
        self.btn_2.setMinimumSize(QtCore.QSize(110, 120))
        self.btn_2.setMaximumSize(QtCore.QSize(110, 120))
        self.btn_2.setText("")
        self.btn_2.setIconSize(QtCore.QSize(120, 120))
        self.btn_2.setObjectName("btn_2")
        self.gridLayout_2.addWidget(self.btn_2, 1, 1, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(Dialog)
        self.btn_4.setMinimumSize(QtCore.QSize(110, 120))
        self.btn_4.setMaximumSize(QtCore.QSize(110, 120))
        self.btn_4.setText("")
        self.btn_4.setIconSize(QtCore.QSize(110, 120))
        self.btn_4.setObjectName("btn_4")
        self.gridLayout_2.addWidget(self.btn_4, 1, 4, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(30, 30))
        self.label_2.setMaximumSize(QtCore.QSize(30, 30))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(30, 30))
        self.label_3.setMaximumSize(QtCore.QSize(30, 30))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(30, 30))
        self.label_4.setMaximumSize(QtCore.QSize(30, 30))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 4, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(30, 30))
        self.label_5.setMaximumSize(QtCore.QSize(30, 30))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 5, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMinimumSize(QtCore.QSize(30, 30))
        self.label_6.setMaximumSize(QtCore.QSize(30, 30))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 6, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setMinimumSize(QtCore.QSize(30, 30))
        self.label_1.setMaximumSize(QtCore.QSize(30, 30))
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_7.addWidget(self.label_1)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_confirm = QtWidgets.QPushButton(Dialog)
        self.btn_confirm.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout_8.addWidget(self.btn_confirm)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "选择换人对象"))
        self.btn_confirm.setText(_translate("Dialog", "确  认"))
