# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectCostumeUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(614, 767)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_costume_pic = QtWidgets.QLabel(self.groupBox)
        self.label_costume_pic.setMinimumSize(QtCore.QSize(110, 120))
        self.label_costume_pic.setMaximumSize(QtCore.QSize(110, 120))
        self.label_costume_pic.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_costume_pic.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_costume_pic.setLineWidth(1)
        self.label_costume_pic.setText("")
        self.label_costume_pic.setObjectName("label_costume_pic")
        self.horizontalLayout_4.addWidget(self.label_costume_pic)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.check_full = QtWidgets.QCheckBox(self.groupBox)
        self.check_full.setObjectName("check_full")
        self.horizontalLayout_11.addWidget(self.check_full)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.box_level = QtWidgets.QSpinBox(self.groupBox)
        self.box_level.setMinimum(1)
        self.box_level.setMaximum(100)
        self.box_level.setObjectName("box_level")
        self.gridLayout_5.addWidget(self.box_level, 0, 1, 1, 1)
        self.box_atk = QtWidgets.QSpinBox(self.groupBox)
        self.box_atk.setMaximum(10000)
        self.box_atk.setObjectName("box_atk")
        self.gridLayout_5.addWidget(self.box_atk, 1, 1, 1, 1)
        self.box_np_start = QtWidgets.QSpinBox(self.groupBox)
        self.box_np_start.setMaximum(500)
        self.box_np_start.setObjectName("box_np_start")
        self.gridLayout_5.addWidget(self.box_np_start, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.box_np_end = QtWidgets.QSpinBox(self.groupBox)
        self.box_np_end.setMaximum(500)
        self.box_np_end.setObjectName("box_np_end")
        self.gridLayout_5.addWidget(self.box_np_end, 3, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 3, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 4, 0, 1, 1)
        self.box_np_event = QtWidgets.QSpinBox(self.groupBox)
        self.box_np_event.setMaximum(500)
        self.box_np_event.setObjectName("box_np_event")
        self.gridLayout_5.addWidget(self.box_np_event, 4, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.box_quick_round = QtWidgets.QSpinBox(self.groupBox)
        self.box_quick_round.setMinimum(-1)
        self.box_quick_round.setProperty("value", -1)
        self.box_quick_round.setObjectName("box_quick_round")
        self.gridLayout.addWidget(self.box_quick_round, 4, 4, 1, 1)
        self.box_attribute_times = QtWidgets.QSpinBox(self.groupBox)
        self.box_attribute_times.setMinimum(-1)
        self.box_attribute_times.setProperty("value", -1)
        self.box_attribute_times.setObjectName("box_attribute_times")
        self.gridLayout.addWidget(self.box_attribute_times, 8, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.box_buster_round = QtWidgets.QSpinBox(self.groupBox)
        self.box_buster_round.setMinimum(-1)
        self.box_buster_round.setProperty("value", -1)
        self.box_buster_round.setObjectName("box_buster_round")
        self.gridLayout.addWidget(self.box_buster_round, 2, 4, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.box_attack = QtWidgets.QSpinBox(self.groupBox)
        self.box_attack.setMinimum(-1000)
        self.box_attack.setMaximum(1000)
        self.box_attack.setObjectName("box_attack")
        self.gridLayout.addWidget(self.box_attack, 1, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 7, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.box_attribute = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_attribute.sizePolicy().hasHeightForWidth())
        self.box_attribute.setSizePolicy(sizePolicy)
        self.box_attribute.setMaximum(10000)
        self.box_attribute.setObjectName("box_attribute")
        self.horizontalLayout.addWidget(self.box_attribute)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 2, 1, 1)
        self.box_oc = QtWidgets.QSpinBox(self.groupBox)
        self.box_oc.setMaximum(4)
        self.box_oc.setObjectName("box_oc")
        self.gridLayout.addWidget(self.box_oc, 7, 2, 1, 1)
        self.box_np_gain_times = QtWidgets.QSpinBox(self.groupBox)
        self.box_np_gain_times.setMinimum(-1)
        self.box_np_gain_times.setProperty("value", -1)
        self.box_np_gain_times.setObjectName("box_np_gain_times")
        self.gridLayout.addWidget(self.box_np_gain_times, 6, 3, 1, 1)
        self.box_oc_round = QtWidgets.QSpinBox(self.groupBox)
        self.box_oc_round.setMinimum(-1)
        self.box_oc_round.setProperty("value", -1)
        self.box_oc_round.setObjectName("box_oc_round")
        self.gridLayout.addWidget(self.box_oc_round, 7, 4, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(70, 0))
        self.label_31.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 0, 4, 1, 1)
        self.box_oc_times = QtWidgets.QSpinBox(self.groupBox)
        self.box_oc_times.setMinimum(-1)
        self.box_oc_times.setProperty("value", -1)
        self.box_oc_times.setObjectName("box_oc_times")
        self.gridLayout.addWidget(self.box_oc_times, 7, 3, 1, 1)
        self.box_arts = QtWidgets.QSpinBox(self.groupBox)
        self.box_arts.setMinimum(-1000)
        self.box_arts.setMaximum(1000)
        self.box_arts.setObjectName("box_arts")
        self.gridLayout.addWidget(self.box_arts, 3, 2, 1, 1)
        self.box_attack_times = QtWidgets.QSpinBox(self.groupBox)
        self.box_attack_times.setMinimum(-1)
        self.box_attack_times.setProperty("value", -1)
        self.box_attack_times.setObjectName("box_attack_times")
        self.gridLayout.addWidget(self.box_attack_times, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.box_np_times = QtWidgets.QSpinBox(self.groupBox)
        self.box_np_times.setMinimum(-1)
        self.box_np_times.setProperty("value", -1)
        self.box_np_times.setObjectName("box_np_times")
        self.gridLayout.addWidget(self.box_np_times, 5, 3, 1, 1)
        self.box_np = QtWidgets.QSpinBox(self.groupBox)
        self.box_np.setMinimum(-1000)
        self.box_np.setMaximum(1000)
        self.box_np.setObjectName("box_np")
        self.gridLayout.addWidget(self.box_np, 5, 2, 1, 1)
        self.box_buster = QtWidgets.QSpinBox(self.groupBox)
        self.box_buster.setMinimum(-1000)
        self.box_buster.setMaximum(1000)
        self.box_buster.setObjectName("box_buster")
        self.gridLayout.addWidget(self.box_buster, 2, 2, 1, 1)
        self.box_quick_times = QtWidgets.QSpinBox(self.groupBox)
        self.box_quick_times.setMinimum(-1)
        self.box_quick_times.setProperty("value", -1)
        self.box_quick_times.setObjectName("box_quick_times")
        self.gridLayout.addWidget(self.box_quick_times, 4, 3, 1, 1)
        self.box_arts_times = QtWidgets.QSpinBox(self.groupBox)
        self.box_arts_times.setMinimum(-1)
        self.box_arts_times.setProperty("value", -1)
        self.box_arts_times.setObjectName("box_arts_times")
        self.gridLayout.addWidget(self.box_arts_times, 3, 3, 1, 1)
        self.box_np_gain = QtWidgets.QSpinBox(self.groupBox)
        self.box_np_gain.setMinimum(-1000)
        self.box_np_gain.setMaximum(1000)
        self.box_np_gain.setObjectName("box_np_gain")
        self.gridLayout.addWidget(self.box_np_gain, 6, 2, 1, 1)
        self.box_arts_round = QtWidgets.QSpinBox(self.groupBox)
        self.box_arts_round.setMinimum(-1)
        self.box_arts_round.setProperty("value", -1)
        self.box_arts_round.setObjectName("box_arts_round")
        self.gridLayout.addWidget(self.box_arts_round, 3, 4, 1, 1)
        self.box_np_gain_round = QtWidgets.QSpinBox(self.groupBox)
        self.box_np_gain_round.setMinimum(-1)
        self.box_np_gain_round.setProperty("value", -1)
        self.box_np_gain_round.setObjectName("box_np_gain_round")
        self.gridLayout.addWidget(self.box_np_gain_round, 6, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.box_attack_round = QtWidgets.QSpinBox(self.groupBox)
        self.box_attack_round.setMinimum(-1)
        self.box_attack_round.setProperty("value", -1)
        self.box_attack_round.setObjectName("box_attack_round")
        self.gridLayout.addWidget(self.box_attack_round, 1, 4, 1, 1)
        self.box_np_round = QtWidgets.QSpinBox(self.groupBox)
        self.box_np_round.setMinimum(-1)
        self.box_np_round.setProperty("value", -1)
        self.box_np_round.setObjectName("box_np_round")
        self.gridLayout.addWidget(self.box_np_round, 5, 4, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_35 = QtWidgets.QLabel(self.groupBox)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_3.addWidget(self.label_35)
        self.lineEdit_attribute = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_attribute.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_attribute.setObjectName("lineEdit_attribute")
        self.horizontalLayout_3.addWidget(self.lineEdit_attribute)
        self.gridLayout.addLayout(self.horizontalLayout_3, 8, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 1, 1, 1)
        self.box_quick = QtWidgets.QSpinBox(self.groupBox)
        self.box_quick.setMinimum(-1000)
        self.box_quick.setMaximum(1000)
        self.box_quick.setObjectName("box_quick")
        self.gridLayout.addWidget(self.box_quick, 4, 2, 1, 1)
        self.box_attribute_round = QtWidgets.QSpinBox(self.groupBox)
        self.box_attribute_round.setMinimum(-1)
        self.box_attribute_round.setProperty("value", -1)
        self.box_attribute_round.setObjectName("box_attribute_round")
        self.gridLayout.addWidget(self.box_attribute_round, 8, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(70, 0))
        self.label_30.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 0, 3, 1, 1)
        self.box_buster_times = QtWidgets.QSpinBox(self.groupBox)
        self.box_buster_times.setMinimum(-1)
        self.box_buster_times.setProperty("value", -1)
        self.box_buster_times.setObjectName("box_buster_times")
        self.gridLayout.addWidget(self.box_buster_times, 2, 3, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.btn_reset = QtWidgets.QPushButton(self.groupBox)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_19.addWidget(self.btn_reset)
        self.btn_confirm = QtWidgets.QPushButton(self.groupBox)
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout_19.addWidget(self.btn_confirm)
        self.btn_cancle = QtWidgets.QPushButton(self.groupBox)
        self.btn_cancle.setObjectName("btn_cancle")
        self.horizontalLayout_19.addWidget(self.btn_cancle)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setMinimumSize(QtCore.QSize(590, 0))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 569, 561))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btn_000 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_000.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_000.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_000.setText("")
        self.btn_000.setIconSize(QtCore.QSize(82, 90))
        self.btn_000.setObjectName("btn_000")
        self.horizontalLayout_14.addWidget(self.btn_000)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 6, 3, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.btn_871 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_871.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_871.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_871.setText("")
        self.btn_871.setIconSize(QtCore.QSize(82, 90))
        self.btn_871.setObjectName("btn_871")
        self.horizontalLayout_22.addWidget(self.btn_871)
        self.gridLayout_3.addLayout(self.horizontalLayout_22, 4, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setMinimumSize(QtCore.QSize(0, 30))
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 5, 0, 1, 1)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.btn_265 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_265.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_265.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_265.setText("")
        self.btn_265.setIconSize(QtCore.QSize(82, 90))
        self.btn_265.setObjectName("btn_265")
        self.horizontalLayout_30.addWidget(self.btn_265)
        self.gridLayout_3.addLayout(self.horizontalLayout_30, 6, 0, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.btn_655 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_655.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_655.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_655.setText("")
        self.btn_655.setIconSize(QtCore.QSize(82, 90))
        self.btn_655.setObjectName("btn_655")
        self.horizontalLayout_25.addWidget(self.btn_655)
        self.gridLayout_3.addLayout(self.horizontalLayout_25, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setMinimumSize(QtCore.QSize(100, 0))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 4, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 5, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 5, 2, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btn_400 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_400.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_400.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_400.setText("")
        self.btn_400.setIconSize(QtCore.QSize(82, 90))
        self.btn_400.setObjectName("btn_400")
        self.horizontalLayout_13.addWidget(self.btn_400)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 6, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_034 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_034.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_034.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_034.setText("")
        self.btn_034.setIconSize(QtCore.QSize(82, 90))
        self.btn_034.setObjectName("btn_034")
        self.horizontalLayout_5.addWidget(self.btn_034)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.btn_570 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_570.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_570.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_570.setText("")
        self.btn_570.setIconSize(QtCore.QSize(82, 90))
        self.btn_570.setObjectName("btn_570")
        self.horizontalLayout_29.addWidget(self.btn_570)
        self.gridLayout_3.addLayout(self.horizontalLayout_29, 2, 4, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.btn_052 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_052.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_052.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_052.setText("")
        self.btn_052.setIconSize(QtCore.QSize(82, 90))
        self.btn_052.setObjectName("btn_052")
        self.horizontalLayout_26.addWidget(self.btn_052)
        self.gridLayout_3.addLayout(self.horizontalLayout_26, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setMinimumSize(QtCore.QSize(100, 30))
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.btn_295 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_295.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_295.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_295.setText("")
        self.btn_295.setIconSize(QtCore.QSize(82, 90))
        self.btn_295.setObjectName("btn_295")
        self.horizontalLayout_24.addWidget(self.btn_295)
        self.gridLayout_3.addLayout(self.horizontalLayout_24, 4, 4, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btn_261 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_261.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_261.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_261.setText("")
        self.btn_261.setIconSize(QtCore.QSize(82, 90))
        self.btn_261.setObjectName("btn_261")
        self.horizontalLayout_15.addWidget(self.btn_261)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_053 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_053.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_053.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_053.setText("")
        self.btn_053.setIconSize(QtCore.QSize(82, 90))
        self.btn_053.setObjectName("btn_053")
        self.horizontalLayout_6.addWidget(self.btn_053)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 4, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 5, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_390 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_390.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_390.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_390.setText("")
        self.btn_390.setIconSize(QtCore.QSize(82, 90))
        self.btn_390.setObjectName("btn_390")
        self.horizontalLayout_8.addWidget(self.btn_390)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 2, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.btn_309 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_309.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_309.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_309.setText("")
        self.btn_309.setIconSize(QtCore.QSize(82, 90))
        self.btn_309.setObjectName("btn_309")
        self.horizontalLayout_28.addWidget(self.btn_309)
        self.gridLayout_3.addLayout(self.horizontalLayout_28, 2, 3, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_048 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_048.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_048.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_048.setText("")
        self.btn_048.setIconSize(QtCore.QSize(82, 90))
        self.btn_048.setObjectName("btn_048")
        self.horizontalLayout_7.addWidget(self.btn_048)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 3, 2, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.btn_792 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_792.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_792.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_792.setText("")
        self.btn_792.setIconSize(QtCore.QSize(82, 90))
        self.btn_792.setObjectName("btn_792")
        self.horizontalLayout_21.addWidget(self.btn_792)
        self.gridLayout_3.addLayout(self.horizontalLayout_21, 4, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 3, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 5, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setMinimumSize(QtCore.QSize(0, 30))
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 7, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btn_181 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_181.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_181.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_181.setText("")
        self.btn_181.setIconSize(QtCore.QSize(82, 90))
        self.btn_181.setObjectName("btn_181")
        self.horizontalLayout_12.addWidget(self.btn_181)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 6, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_683 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_683.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_683.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_683.setText("")
        self.btn_683.setIconSize(QtCore.QSize(82, 90))
        self.btn_683.setObjectName("btn_683")
        self.horizontalLayout_9.addWidget(self.btn_683)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 0, 3, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.btn_1126 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_1126.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_1126.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_1126.setText("")
        self.btn_1126.setIconSize(QtCore.QSize(82, 90))
        self.btn_1126.setObjectName("btn_1126")
        self.horizontalLayout_23.addWidget(self.btn_1126)
        self.gridLayout_3.addLayout(self.horizontalLayout_23, 4, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setMinimumSize(QtCore.QSize(100, 0))
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 7, 3, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.btn_028 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_028.setMinimumSize(QtCore.QSize(82, 90))
        self.btn_028.setMaximumSize(QtCore.QSize(82, 90))
        self.btn_028.setText("")
        self.btn_028.setIconSize(QtCore.QSize(82, 90))
        self.btn_028.setObjectName("btn_028")
        self.horizontalLayout_27.addWidget(self.btn_028)
        self.gridLayout_3.addLayout(self.horizontalLayout_27, 2, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 7, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "选择概念礼装"))
        self.groupBox.setTitle(_translate("Dialog", "礼装数据"))
        self.check_full.setText(_translate("Dialog", " 满 破"))
        self.label_11.setText(_translate("Dialog", "等级"))
        self.label_12.setText(_translate("Dialog", "ATK"))
        self.label_10.setText(_translate("Dialog", "初始NP"))
        self.label_28.setText(_translate("Dialog", "退场NP增加 "))
        self.label_33.setText(_translate("Dialog", "活动攻击力提升"))
        self.label_5.setText(_translate("Dialog", "宝具威力提升"))
        self.label_29.setText(_translate("Dialog", "幅  度"))
        self.label_4.setText(_translate("Dialog", "攻击力提升"))
        self.label_32.setText(_translate("Dialog", "充能阶段上升"))
        self.label_31.setText(_translate("Dialog", "回 合"))
        self.label.setText(_translate("Dialog", "Buster提升"))
        self.label_2.setText(_translate("Dialog", "Arts提升"))
        self.label_35.setText(_translate("Dialog", "特攻"))
        self.label_6.setText(_translate("Dialog", "NP获得量提升"))
        self.label_3.setText(_translate("Dialog", "Quick提升"))
        self.label_30.setText(_translate("Dialog", "次 数"))
        self.btn_reset.setText(_translate("Dialog", "清   空"))
        self.btn_confirm.setText(_translate("Dialog", "确  认"))
        self.btn_cancle.setText(_translate("Dialog", "取  消"))
        self.groupBox_2.setTitle(_translate("Dialog", "礼装列表"))
        self.label_17.setText(_translate("Dialog", "潜入湛蓝"))
        self.label_15.setText(_translate("Dialog", "黄金相扑"))
        self.label_22.setText(_translate("Dialog", "去往远方的巡礼"))
        self.label_23.setText(_translate("Dialog", "绘画之夏"))
        self.label_14.setText(_translate("Dialog", "万圣节小恶魔"))
        self.label_7.setText(_translate("Dialog", "万华镜"))
        self.label_18.setText(_translate("Dialog", "万圣节公主"))
        self.label_16.setText(_translate("Dialog", "某个夏天"))
        self.label_26.setText(_translate("Dialog", "圣诞节的轨迹"))
        self.label_8.setText(_translate("Dialog", "黑之圣杯"))
        self.label_19.setText(_translate("Dialog", "虚数魔术"))
        self.label_20.setText(_translate("Dialog", "苍玉之魔法少女"))
        self.label_27.setText(_translate("Dialog", "海军骑士"))
        self.label_24.setText(_translate("Dialog", "卡姆兰之战"))
        self.label_25.setText(_translate("Dialog", "无慈悲者"))
        self.label_9.setText(_translate("Dialog", "圣夜晚餐"))
        self.label_13.setText(_translate("Dialog", "天际旋荡"))
        self.label_21.setText(_translate("Dialog", "自定义"))
        self.label_34.setText(_translate("Dialog", "魔性菩萨"))
