# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectMasterUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(646, 711)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_data_reset = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_data_reset.setObjectName("btn_data_reset")
        self.horizontalLayout_3.addWidget(self.btn_data_reset)
        self.btn_data_input = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_data_input.setEnabled(False)
        self.btn_data_input.setObjectName("btn_data_input")
        self.horizontalLayout_3.addWidget(self.btn_data_input)
        self.btn_data_output = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_data_output.setObjectName("btn_data_output")
        self.horizontalLayout_3.addWidget(self.btn_data_output)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_master_pic_a = QtWidgets.QLabel(self.groupBox_2)
        self.label_master_pic_a.setMinimumSize(QtCore.QSize(110, 120))
        self.label_master_pic_a.setMaximumSize(QtCore.QSize(110, 120))
        self.label_master_pic_a.setText("")
        self.label_master_pic_a.setObjectName("label_master_pic_a")
        self.horizontalLayout.addWidget(self.label_master_pic_a)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_master_level = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_master_level.sizePolicy().hasHeightForWidth())
        self.label_master_level.setSizePolicy(sizePolicy)
        self.label_master_level.setMinimumSize(QtCore.QSize(80, 0))
        self.label_master_level.setAlignment(QtCore.Qt.AlignCenter)
        self.label_master_level.setObjectName("label_master_level")
        self.verticalLayout_6.addWidget(self.label_master_level)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bar_master_level = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar_master_level.sizePolicy().hasHeightForWidth())
        self.bar_master_level.setSizePolicy(sizePolicy)
        self.bar_master_level.setMinimumSize(QtCore.QSize(0, 220))
        self.bar_master_level.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bar_master_level.setMinimum(1)
        self.bar_master_level.setMaximum(10)
        self.bar_master_level.setSingleStep(1)
        self.bar_master_level.setPageStep(1)
        self.bar_master_level.setProperty("value", 9)
        self.bar_master_level.setOrientation(QtCore.Qt.Vertical)
        self.bar_master_level.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bar_master_level.setObjectName("bar_master_level")
        self.horizontalLayout_2.addWidget(self.bar_master_level)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_name = QtWidgets.QLabel(self.groupBox_2)
        self.label_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.verticalLayout_3.addWidget(self.label_name)
        self.label_skill_1 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_skill_1.sizePolicy().hasHeightForWidth())
        self.label_skill_1.setSizePolicy(sizePolicy)
        self.label_skill_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_skill_1.setObjectName("label_skill_1")
        self.verticalLayout_3.addWidget(self.label_skill_1)
        self.label_skill_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_skill_2.sizePolicy().hasHeightForWidth())
        self.label_skill_2.setSizePolicy(sizePolicy)
        self.label_skill_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_skill_2.setObjectName("label_skill_2")
        self.verticalLayout_3.addWidget(self.label_skill_2)
        self.label_skill_3 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_skill_3.sizePolicy().hasHeightForWidth())
        self.label_skill_3.setSizePolicy(sizePolicy)
        self.label_skill_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_skill_3.setObjectName("label_skill_3")
        self.verticalLayout_3.addWidget(self.label_skill_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_clear = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_8.addWidget(self.btn_clear)
        self.btn_confirm = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout_8.addWidget(self.btn_confirm)
        self.btn_cancel = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_8.addWidget(self.btn_cancel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setMinimumSize(QtCore.QSize(600, 0))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 579, 487))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_master_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_15.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_15.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_15.setText("")
        self.btn_master_15.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_15.setObjectName("btn_master_15")
        self.gridLayout_2.addWidget(self.btn_master_15, 2, 4, 1, 1)
        self.btn_master_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_6.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_6.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_6.setText("")
        self.btn_master_6.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_6.setObjectName("btn_master_6")
        self.gridLayout_2.addWidget(self.btn_master_6, 1, 0, 1, 1)
        self.btn_master_21 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_21.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_21.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_21.setText("")
        self.btn_master_21.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_21.setObjectName("btn_master_21")
        self.gridLayout_2.addWidget(self.btn_master_21, 4, 0, 1, 1)
        self.btn_master_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_10.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_10.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_10.setText("")
        self.btn_master_10.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_10.setObjectName("btn_master_10")
        self.gridLayout_2.addWidget(self.btn_master_10, 1, 4, 1, 1)
        self.btn_master_23 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_23.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_23.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_23.setText("")
        self.btn_master_23.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_23.setObjectName("btn_master_23")
        self.gridLayout_2.addWidget(self.btn_master_23, 4, 2, 1, 1)
        self.btn_master_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_17.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_17.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_17.setText("")
        self.btn_master_17.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_17.setObjectName("btn_master_17")
        self.gridLayout_2.addWidget(self.btn_master_17, 3, 1, 1, 1)
        self.btn_master_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_8.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_8.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_8.setText("")
        self.btn_master_8.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_8.setObjectName("btn_master_8")
        self.gridLayout_2.addWidget(self.btn_master_8, 1, 2, 1, 1)
        self.btn_master_22 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_22.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_22.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_22.setText("")
        self.btn_master_22.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_22.setObjectName("btn_master_22")
        self.gridLayout_2.addWidget(self.btn_master_22, 4, 1, 1, 1)
        self.btn_master_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_13.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_13.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_13.setText("")
        self.btn_master_13.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_13.setObjectName("btn_master_13")
        self.gridLayout_2.addWidget(self.btn_master_13, 2, 2, 1, 1)
        self.btn_master_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_3.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_3.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_3.setText("")
        self.btn_master_3.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_3.setObjectName("btn_master_3")
        self.gridLayout_2.addWidget(self.btn_master_3, 0, 2, 1, 1)
        self.btn_master_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_9.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_9.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_9.setText("")
        self.btn_master_9.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_9.setObjectName("btn_master_9")
        self.gridLayout_2.addWidget(self.btn_master_9, 1, 3, 1, 1)
        self.btn_master_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_5.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_5.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_5.setText("")
        self.btn_master_5.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_5.setObjectName("btn_master_5")
        self.gridLayout_2.addWidget(self.btn_master_5, 0, 4, 1, 1)
        self.btn_master_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_18.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_18.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_18.setText("")
        self.btn_master_18.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_18.setObjectName("btn_master_18")
        self.gridLayout_2.addWidget(self.btn_master_18, 3, 2, 1, 1)
        self.btn_master_24 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_24.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_24.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_24.setText("")
        self.btn_master_24.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_24.setObjectName("btn_master_24")
        self.gridLayout_2.addWidget(self.btn_master_24, 4, 3, 1, 1)
        self.btn_master_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_14.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_14.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_14.setText("")
        self.btn_master_14.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_14.setObjectName("btn_master_14")
        self.gridLayout_2.addWidget(self.btn_master_14, 2, 3, 1, 1)
        self.btn_master_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_4.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_4.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_4.setText("")
        self.btn_master_4.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_4.setObjectName("btn_master_4")
        self.gridLayout_2.addWidget(self.btn_master_4, 0, 3, 1, 1)
        self.btn_master_20 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_20.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_20.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_20.setText("")
        self.btn_master_20.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_20.setObjectName("btn_master_20")
        self.gridLayout_2.addWidget(self.btn_master_20, 3, 4, 1, 1)
        self.btn_master_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_7.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_7.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_7.setText("")
        self.btn_master_7.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_7.setObjectName("btn_master_7")
        self.gridLayout_2.addWidget(self.btn_master_7, 1, 1, 1, 1)
        self.btn_master_19 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_19.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_19.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_19.setText("")
        self.btn_master_19.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_19.setObjectName("btn_master_19")
        self.gridLayout_2.addWidget(self.btn_master_19, 3, 3, 1, 1)
        self.btn_master_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_2.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_2.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_2.setText("")
        self.btn_master_2.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_2.setObjectName("btn_master_2")
        self.gridLayout_2.addWidget(self.btn_master_2, 0, 1, 1, 1)
        self.btn_master_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_12.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_12.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_12.setText("")
        self.btn_master_12.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_12.setObjectName("btn_master_12")
        self.gridLayout_2.addWidget(self.btn_master_12, 2, 1, 1, 1)
        self.btn_master_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_16.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_16.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_16.setText("")
        self.btn_master_16.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_16.setObjectName("btn_master_16")
        self.gridLayout_2.addWidget(self.btn_master_16, 3, 0, 1, 1)
        self.btn_master_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_1.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_1.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_1.setText("")
        self.btn_master_1.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_1.setObjectName("btn_master_1")
        self.gridLayout_2.addWidget(self.btn_master_1, 0, 0, 1, 1)
        self.btn_master_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_11.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_11.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_11.setText("")
        self.btn_master_11.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_11.setObjectName("btn_master_11")
        self.gridLayout_2.addWidget(self.btn_master_11, 2, 0, 1, 1)
        self.btn_master_25 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_master_25.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_master_25.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_master_25.setText("")
        self.btn_master_25.setIconSize(QtCore.QSize(80, 87))
        self.btn_master_25.setObjectName("btn_master_25")
        self.gridLayout_2.addWidget(self.btn_master_25, 4, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "选择魔术礼装"))
        self.groupBox_2.setTitle(_translate("Dialog", "设置魔术礼装"))
        self.btn_data_reset.setText(_translate("Dialog", "还原数据"))
        self.btn_data_input.setText(_translate("Dialog", "导入数据(带开发)"))
        self.btn_data_output.setText(_translate("Dialog", "保存数据"))
        self.label_master_level.setText(_translate("Dialog", "等级"))
        self.label_name.setText(_translate("Dialog", "名称:"))
        self.label_skill_1.setText(_translate("Dialog", "技能1: "))
        self.label_skill_2.setText(_translate("Dialog", "技能2: "))
        self.label_skill_3.setText(_translate("Dialog", "技能3: "))
        self.btn_clear.setText(_translate("Dialog", "清  空"))
        self.btn_confirm.setText(_translate("Dialog", "确  认"))
        self.btn_cancel.setText(_translate("Dialog", "取  消"))
        self.groupBox.setTitle(_translate("Dialog", "魔术礼装列表"))
