# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectLevelUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(977, 657)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.box_choose_event = QtWidgets.QComboBox(Dialog)
        self.box_choose_event.setObjectName("box_choose_event")
        self.horizontalLayout.addWidget(self.box_choose_event)
        self.box_choose_section = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_choose_section.sizePolicy().hasHeightForWidth())
        self.box_choose_section.setSizePolicy(sizePolicy)
        self.box_choose_section.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.box_choose_section.setObjectName("box_choose_section")
        self.horizontalLayout.addWidget(self.box_choose_section)
        self.box_choose_level = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_choose_level.sizePolicy().hasHeightForWidth())
        self.box_choose_level.setSizePolicy(sizePolicy)
        self.box_choose_level.setObjectName("box_choose_level")
        self.horizontalLayout.addWidget(self.box_choose_level)
        self.btn_confirm = QtWidgets.QPushButton(Dialog)
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout.addWidget(self.btn_confirm)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.line_battle_ground = QtWidgets.QLineEdit(Dialog)
        self.line_battle_ground.setObjectName("line_battle_ground")
        self.horizontalLayout_11.addWidget(self.line_battle_ground)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 5, 3, 1, 1)
        self.line_9 = QtWidgets.QFrame(Dialog)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 1, 5, 1, 1)
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 3, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 5, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(Dialog)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 3, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 3, 3, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pic_round1_enemy3 = QtWidgets.QLabel(Dialog)
        self.pic_round1_enemy3.setMinimumSize(QtCore.QSize(63, 63))
        self.pic_round1_enemy3.setMaximumSize(QtCore.QSize(63, 63))
        self.pic_round1_enemy3.setText("")
        self.pic_round1_enemy3.setObjectName("pic_round1_enemy3")
        self.horizontalLayout_2.addWidget(self.pic_round1_enemy3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.round1_enemy3_np_type = QtWidgets.QCheckBox(Dialog)
        self.round1_enemy3_np_type.setObjectName("round1_enemy3_np_type")
        self.verticalLayout_3.addWidget(self.round1_enemy3_np_type)
        self.label_round1_enemy3 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_round1_enemy3.sizePolicy().hasHeightForWidth())
        self.label_round1_enemy3.setSizePolicy(sizePolicy)
        self.label_round1_enemy3.setText("")
        self.label_round1_enemy3.setObjectName("label_round1_enemy3")
        self.verticalLayout_3.addWidget(self.label_round1_enemy3)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pic_round1_enemy2 = QtWidgets.QLabel(Dialog)
        self.pic_round1_enemy2.setMinimumSize(QtCore.QSize(63, 63))
        self.pic_round1_enemy2.setMaximumSize(QtCore.QSize(63, 63))
        self.pic_round1_enemy2.setText("")
        self.pic_round1_enemy2.setObjectName("pic_round1_enemy2")
        self.horizontalLayout_3.addWidget(self.pic_round1_enemy2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.round1_enemy2_np_type = QtWidgets.QCheckBox(Dialog)
        self.round1_enemy2_np_type.setObjectName("round1_enemy2_np_type")
        self.verticalLayout_4.addWidget(self.round1_enemy2_np_type)
        self.label_round1_enemy2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_round1_enemy2.sizePolicy().hasHeightForWidth())
        self.label_round1_enemy2.setSizePolicy(sizePolicy)
        self.label_round1_enemy2.setText("")
        self.label_round1_enemy2.setObjectName("label_round1_enemy2")
        self.verticalLayout_4.addWidget(self.label_round1_enemy2)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 4, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pic_round1_enemy1 = QtWidgets.QLabel(Dialog)
        self.pic_round1_enemy1.setMinimumSize(QtCore.QSize(63, 63))
        self.pic_round1_enemy1.setMaximumSize(QtCore.QSize(63, 63))
        self.pic_round1_enemy1.setText("")
        self.pic_round1_enemy1.setObjectName("pic_round1_enemy1")
        self.horizontalLayout_4.addWidget(self.pic_round1_enemy1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.round1_enemy1_np_type = QtWidgets.QCheckBox(Dialog)
        self.round1_enemy1_np_type.setObjectName("round1_enemy1_np_type")
        self.verticalLayout_5.addWidget(self.round1_enemy1_np_type)
        self.label_round1_enemy1 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_round1_enemy1.sizePolicy().hasHeightForWidth())
        self.label_round1_enemy1.setSizePolicy(sizePolicy)
        self.label_round1_enemy1.setText("")
        self.label_round1_enemy1.setObjectName("label_round1_enemy1")
        self.verticalLayout_5.addWidget(self.label_round1_enemy1)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 6, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pic_round2_enemy3 = QtWidgets.QLabel(Dialog)
        self.pic_round2_enemy3.setMinimumSize(QtCore.QSize(63, 63))
        self.pic_round2_enemy3.setMaximumSize(QtCore.QSize(63, 63))
        self.pic_round2_enemy3.setText("")
        self.pic_round2_enemy3.setObjectName("pic_round2_enemy3")
        self.horizontalLayout_5.addWidget(self.pic_round2_enemy3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.round2_enemy3_np_type = QtWidgets.QCheckBox(Dialog)
        self.round2_enemy3_np_type.setObjectName("round2_enemy3_np_type")
        self.verticalLayout_6.addWidget(self.round2_enemy3_np_type)
        self.label_round2_enemy3 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_round2_enemy3.sizePolicy().hasHeightForWidth())
        self.label_round2_enemy3.setSizePolicy(sizePolicy)
        self.label_round2_enemy3.setText("")
        self.label_round2_enemy3.setObjectName("label_round2_enemy3")
        self.verticalLayout_6.addWidget(self.label_round2_enemy3)
        self.gridLayout.addLayout(self.verticalLayout_6, 3, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pic_round2_enemy2 = QtWidgets.QLabel(Dialog)
        self.pic_round2_enemy2.setMinimumSize(QtCore.QSize(63, 63))
        self.pic_round2_enemy2.setMaximumSize(QtCore.QSize(63, 63))
        self.pic_round2_enemy2.setText("")
        self.pic_round2_enemy2.setObjectName("pic_round2_enemy2")
        self.horizontalLayout_6.addWidget(self.pic_round2_enemy2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.round2_enemy2_np_type = QtWidgets.QCheckBox(Dialog)
        self.round2_enemy2_np_type.setObjectName("round2_enemy2_np_type")
        self.verticalLayout_7.addWidget(self.round2_enemy2_np_type)
        self.label_round2_enemy2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_round2_enemy2.sizePolicy().hasHeightForWidth())
        self.label_round2_enemy2.setSizePolicy(sizePolicy)
        self.label_round2_enemy2.setText("")
        self.label_round2_enemy2.setObjectName("label_round2_enemy2")
        self.verticalLayout_7.addWidget(self.label_round2_enemy2)
        self.gridLayout.addLayout(self.verticalLayout_7, 3, 4, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pic_round2_enemy1 = QtWidgets.QLabel(Dialog)
        self.pic_round2_enemy1.setMinimumSize(QtCore.QSize(63, 63))
        self.pic_round2_enemy1.setMaximumSize(QtCore.QSize(63, 63))
        self.pic_round2_enemy1.setText("")
        self.pic_round2_enemy1.setObjectName("pic_round2_enemy1")
        self.horizontalLayout_7.addWidget(self.pic_round2_enemy1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.round2_enemy1_np_type = QtWidgets.QCheckBox(Dialog)
        self.round2_enemy1_np_type.setObjectName("round2_enemy1_np_type")
        self.verticalLayout_8.addWidget(self.round2_enemy1_np_type)
        self.label_round2_enemy1 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_round2_enemy1.sizePolicy().hasHeightForWidth())
        self.label_round2_enemy1.setSizePolicy(sizePolicy)
        self.label_round2_enemy1.setText("")
        self.label_round2_enemy1.setObjectName("label_round2_enemy1")
        self.verticalLayout_8.addWidget(self.label_round2_enemy1)
        self.gridLayout.addLayout(self.verticalLayout_8, 3, 6, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pic_round3_enemy3 = QtWidgets.QLabel(Dialog)
        self.pic_round3_enemy3.setMinimumSize(QtCore.QSize(63, 63))
        self.pic_round3_enemy3.setMaximumSize(QtCore.QSize(63, 63))
        self.pic_round3_enemy3.setText("")
        self.pic_round3_enemy3.setObjectName("pic_round3_enemy3")
        self.horizontalLayout_8.addWidget(self.pic_round3_enemy3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.round3_enemy3_np_type = QtWidgets.QCheckBox(Dialog)
        self.round3_enemy3_np_type.setObjectName("round3_enemy3_np_type")
        self.verticalLayout_9.addWidget(self.round3_enemy3_np_type)
        self.label_round3_enemy3 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_round3_enemy3.sizePolicy().hasHeightForWidth())
        self.label_round3_enemy3.setSizePolicy(sizePolicy)
        self.label_round3_enemy3.setText("")
        self.label_round3_enemy3.setObjectName("label_round3_enemy3")
        self.verticalLayout_9.addWidget(self.label_round3_enemy3)
        self.gridLayout.addLayout(self.verticalLayout_9, 5, 2, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pic_round3_enemy2 = QtWidgets.QLabel(Dialog)
        self.pic_round3_enemy2.setMinimumSize(QtCore.QSize(63, 63))
        self.pic_round3_enemy2.setMaximumSize(QtCore.QSize(63, 63))
        self.pic_round3_enemy2.setText("")
        self.pic_round3_enemy2.setObjectName("pic_round3_enemy2")
        self.horizontalLayout_9.addWidget(self.pic_round3_enemy2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.round3_enemy2_np_type = QtWidgets.QCheckBox(Dialog)
        self.round3_enemy2_np_type.setObjectName("round3_enemy2_np_type")
        self.verticalLayout_11.addWidget(self.round3_enemy2_np_type)
        self.label_round3_enemy2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_round3_enemy2.sizePolicy().hasHeightForWidth())
        self.label_round3_enemy2.setSizePolicy(sizePolicy)
        self.label_round3_enemy2.setText("")
        self.label_round3_enemy2.setObjectName("label_round3_enemy2")
        self.verticalLayout_11.addWidget(self.label_round3_enemy2)
        self.gridLayout.addLayout(self.verticalLayout_11, 5, 4, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pic_round3_enemy1 = QtWidgets.QLabel(Dialog)
        self.pic_round3_enemy1.setMinimumSize(QtCore.QSize(63, 63))
        self.pic_round3_enemy1.setMaximumSize(QtCore.QSize(63, 63))
        self.pic_round3_enemy1.setText("")
        self.pic_round3_enemy1.setObjectName("pic_round3_enemy1")
        self.horizontalLayout_10.addWidget(self.pic_round3_enemy1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.round3_enemy1_np_type = QtWidgets.QCheckBox(Dialog)
        self.round3_enemy1_np_type.setObjectName("round3_enemy1_np_type")
        self.verticalLayout_12.addWidget(self.round3_enemy1_np_type)
        self.label_round3_enemy1 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_round3_enemy1.sizePolicy().hasHeightForWidth())
        self.label_round3_enemy1.setSizePolicy(sizePolicy)
        self.label_round3_enemy1.setText("")
        self.label_round3_enemy1.setObjectName("label_round3_enemy1")
        self.verticalLayout_12.addWidget(self.label_round3_enemy1)
        self.gridLayout.addLayout(self.verticalLayout_12, 5, 6, 1, 1)
        self.line_11 = QtWidgets.QFrame(Dialog)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 1, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(Dialog)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 2, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(Dialog)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 4, 0, 1, 1)
        self.line_13 = QtWidgets.QFrame(Dialog)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 2, 2, 1, 1)
        self.line_14 = QtWidgets.QFrame(Dialog)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout.addWidget(self.line_14, 2, 4, 1, 1)
        self.line_15 = QtWidgets.QFrame(Dialog)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout.addWidget(self.line_15, 2, 6, 1, 1)
        self.line_16 = QtWidgets.QFrame(Dialog)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout.addWidget(self.line_16, 4, 2, 1, 1)
        self.line_17 = QtWidgets.QFrame(Dialog)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout.addWidget(self.line_17, 4, 4, 1, 1)
        self.line_18 = QtWidgets.QFrame(Dialog)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout.addWidget(self.line_18, 4, 6, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "选择关卡"))
        self.label.setText(_translate("Dialog", "选择关卡"))
        self.btn_confirm.setText(_translate("Dialog", "确  认"))
        self.label_3.setText(_translate("Dialog", "战斗场景"))
        self.label_2.setText(_translate("Dialog", "注：不同战斗场景之间请用\",\"进行分割。目前活动关卡均没有战斗场景数据, 请手动添加"))
        self.label_12.setText(_translate("Dialog", "回合2"))
        self.label_11.setText(_translate("Dialog", "回合3"))
        self.label_10.setText(_translate("Dialog", "回合1"))
        self.round1_enemy3_np_type.setText(_translate("Dialog", "死灵补正"))
        self.round1_enemy2_np_type.setText(_translate("Dialog", "死灵补正"))
        self.round1_enemy1_np_type.setText(_translate("Dialog", "死灵补正"))
        self.round2_enemy3_np_type.setText(_translate("Dialog", "死灵补正"))
        self.round2_enemy2_np_type.setText(_translate("Dialog", "死灵补正"))
        self.round2_enemy1_np_type.setText(_translate("Dialog", "死灵补正"))
        self.round3_enemy3_np_type.setText(_translate("Dialog", "死灵补正"))
        self.round3_enemy2_np_type.setText(_translate("Dialog", "死灵补正"))
        self.round3_enemy1_np_type.setText(_translate("Dialog", "死灵补正"))
