# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectServantUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(654, 765)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_data_reset = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_data_reset.setObjectName("btn_data_reset")
        self.horizontalLayout_3.addWidget(self.btn_data_reset)
        self.btn_data_input = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_data_input.setEnabled(False)
        self.btn_data_input.setObjectName("btn_data_input")
        self.horizontalLayout_3.addWidget(self.btn_data_input)
        self.btn_data_output = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_data_output.setObjectName("btn_data_output")
        self.horizontalLayout_3.addWidget(self.btn_data_output)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_servant_pic = QtWidgets.QLabel(self.groupBox_2)
        self.label_servant_pic.setMinimumSize(QtCore.QSize(110, 120))
        self.label_servant_pic.setMaximumSize(QtCore.QSize(110, 120))
        self.label_servant_pic.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_servant_pic.setText("")
        self.label_servant_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servant_pic.setObjectName("label_servant_pic")
        self.verticalLayout_7.addWidget(self.label_servant_pic)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_servant_level = QtWidgets.QLabel(self.groupBox_2)
        self.label_servant_level.setMinimumSize(QtCore.QSize(72, 0))
        self.label_servant_level.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servant_level.setObjectName("label_servant_level")
        self.verticalLayout_6.addWidget(self.label_servant_level)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bar_servant_holygrail = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar_servant_holygrail.sizePolicy().hasHeightForWidth())
        self.bar_servant_holygrail.setSizePolicy(sizePolicy)
        self.bar_servant_holygrail.setMinimumSize(QtCore.QSize(0, 100))
        self.bar_servant_holygrail.setMinimum(0)
        self.bar_servant_holygrail.setMaximum(9)
        self.bar_servant_holygrail.setSingleStep(1)
        self.bar_servant_holygrail.setPageStep(1)
        self.bar_servant_holygrail.setProperty("value", 9)
        self.bar_servant_holygrail.setOrientation(QtCore.Qt.Vertical)
        self.bar_servant_holygrail.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bar_servant_holygrail.setObjectName("bar_servant_holygrail")
        self.horizontalLayout_2.addWidget(self.bar_servant_holygrail)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_servant_np = QtWidgets.QLabel(self.groupBox_2)
        self.label_servant_np.setMinimumSize(QtCore.QSize(72, 0))
        self.label_servant_np.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servant_np.setObjectName("label_servant_np")
        self.verticalLayout_5.addWidget(self.label_servant_np)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bar_servant_np = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar_servant_np.sizePolicy().hasHeightForWidth())
        self.bar_servant_np.setSizePolicy(sizePolicy)
        self.bar_servant_np.setMinimumSize(QtCore.QSize(0, 100))
        self.bar_servant_np.setMinimum(1)
        self.bar_servant_np.setMaximum(5)
        self.bar_servant_np.setPageStep(1)
        self.bar_servant_np.setProperty("value", 1)
        self.bar_servant_np.setOrientation(QtCore.Qt.Vertical)
        self.bar_servant_np.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bar_servant_np.setObjectName("bar_servant_np")
        self.horizontalLayout_4.addWidget(self.bar_servant_np)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_servant_fufu = QtWidgets.QLabel(self.groupBox_2)
        self.label_servant_fufu.setMinimumSize(QtCore.QSize(80, 0))
        self.label_servant_fufu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servant_fufu.setObjectName("label_servant_fufu")
        self.verticalLayout_8.addWidget(self.label_servant_fufu)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.bar_servant_fufu = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar_servant_fufu.sizePolicy().hasHeightForWidth())
        self.bar_servant_fufu.setSizePolicy(sizePolicy)
        self.bar_servant_fufu.setMinimumSize(QtCore.QSize(0, 100))
        self.bar_servant_fufu.setMaximum(200)
        self.bar_servant_fufu.setSingleStep(1)
        self.bar_servant_fufu.setPageStep(1)
        self.bar_servant_fufu.setProperty("value", 100)
        self.bar_servant_fufu.setOrientation(QtCore.Qt.Vertical)
        self.bar_servant_fufu.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bar_servant_fufu.setTickInterval(20)
        self.bar_servant_fufu.setObjectName("bar_servant_fufu")
        self.horizontalLayout_9.addWidget(self.bar_servant_fufu)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_servant_skill1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_servant_skill1.setMinimumSize(QtCore.QSize(72, 0))
        self.label_servant_skill1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servant_skill1.setObjectName("label_servant_skill1")
        self.verticalLayout_4.addWidget(self.label_servant_skill1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bar_servant_skill1 = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar_servant_skill1.sizePolicy().hasHeightForWidth())
        self.bar_servant_skill1.setSizePolicy(sizePolicy)
        self.bar_servant_skill1.setMinimumSize(QtCore.QSize(0, 100))
        self.bar_servant_skill1.setMinimum(1)
        self.bar_servant_skill1.setMaximum(10)
        self.bar_servant_skill1.setPageStep(1)
        self.bar_servant_skill1.setProperty("value", 1)
        self.bar_servant_skill1.setOrientation(QtCore.Qt.Vertical)
        self.bar_servant_skill1.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bar_servant_skill1.setObjectName("bar_servant_skill1")
        self.horizontalLayout_5.addWidget(self.bar_servant_skill1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_servant_skill2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_servant_skill2.setMinimumSize(QtCore.QSize(72, 0))
        self.label_servant_skill2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servant_skill2.setObjectName("label_servant_skill2")
        self.verticalLayout_3.addWidget(self.label_servant_skill2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bar_servant_skill2 = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar_servant_skill2.sizePolicy().hasHeightForWidth())
        self.bar_servant_skill2.setSizePolicy(sizePolicy)
        self.bar_servant_skill2.setMinimumSize(QtCore.QSize(0, 100))
        self.bar_servant_skill2.setMinimum(1)
        self.bar_servant_skill2.setMaximum(10)
        self.bar_servant_skill2.setPageStep(1)
        self.bar_servant_skill2.setProperty("value", 1)
        self.bar_servant_skill2.setOrientation(QtCore.Qt.Vertical)
        self.bar_servant_skill2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bar_servant_skill2.setObjectName("bar_servant_skill2")
        self.horizontalLayout_6.addWidget(self.bar_servant_skill2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_servant_skill3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_servant_skill3.setMinimumSize(QtCore.QSize(72, 0))
        self.label_servant_skill3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servant_skill3.setObjectName("label_servant_skill3")
        self.verticalLayout.addWidget(self.label_servant_skill3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bar_servant_skill3 = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar_servant_skill3.sizePolicy().hasHeightForWidth())
        self.bar_servant_skill3.setSizePolicy(sizePolicy)
        self.bar_servant_skill3.setMinimumSize(QtCore.QSize(0, 100))
        self.bar_servant_skill3.setMinimum(1)
        self.bar_servant_skill3.setMaximum(10)
        self.bar_servant_skill3.setPageStep(1)
        self.bar_servant_skill3.setProperty("value", 1)
        self.bar_servant_skill3.setOrientation(QtCore.Qt.Vertical)
        self.bar_servant_skill3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bar_servant_skill3.setObjectName("bar_servant_skill3")
        self.horizontalLayout_7.addWidget(self.bar_servant_skill3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_clear = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_8.addWidget(self.btn_clear)
        self.btn_confirm = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout_8.addWidget(self.btn_confirm)
        self.btn_cancel = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_8.addWidget(self.btn_cancel)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_kongming = QtWidgets.QPushButton(self.groupBox)
        self.btn_kongming.setObjectName("btn_kongming")
        self.horizontalLayout_10.addWidget(self.btn_kongming)
        self.btn_merlin = QtWidgets.QPushButton(self.groupBox)
        self.btn_merlin.setObjectName("btn_merlin")
        self.horizontalLayout_10.addWidget(self.btn_merlin)
        self.btn_cba = QtWidgets.QPushButton(self.groupBox)
        self.btn_cba.setObjectName("btn_cba")
        self.horizontalLayout_10.addWidget(self.btn_cba)
        self.btn_tamamo = QtWidgets.QPushButton(self.groupBox)
        self.btn_tamamo.setObjectName("btn_tamamo")
        self.horizontalLayout_10.addWidget(self.btn_tamamo)
        self.btn_nero_bride = QtWidgets.QPushButton(self.groupBox)
        self.btn_nero_bride.setObjectName("btn_nero_bride")
        self.horizontalLayout_10.addWidget(self.btn_nero_bride)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_lancer = QtWidgets.QPushButton(self.groupBox)
        self.btn_lancer.setObjectName("btn_lancer")
        self.gridLayout.addWidget(self.btn_lancer, 1, 3, 1, 1)
        self.btn_lowstars = QtWidgets.QPushButton(self.groupBox)
        self.btn_lowstars.setObjectName("btn_lowstars")
        self.gridLayout.addWidget(self.btn_lowstars, 3, 0, 1, 1)
        self.btn_4stars = QtWidgets.QPushButton(self.groupBox)
        self.btn_4stars.setObjectName("btn_4stars")
        self.gridLayout.addWidget(self.btn_4stars, 2, 0, 1, 1)
        self.btn_caster = QtWidgets.QPushButton(self.groupBox)
        self.btn_caster.setObjectName("btn_caster")
        self.gridLayout.addWidget(self.btn_caster, 2, 1, 1, 1)
        self.btn_archer = QtWidgets.QPushButton(self.groupBox)
        self.btn_archer.setObjectName("btn_archer")
        self.gridLayout.addWidget(self.btn_archer, 1, 2, 1, 1)
        self.btn_extra = QtWidgets.QPushButton(self.groupBox)
        self.btn_extra.setObjectName("btn_extra")
        self.gridLayout.addWidget(self.btn_extra, 2, 4, 1, 1)
        self.btn_berserker = QtWidgets.QPushButton(self.groupBox)
        self.btn_berserker.setObjectName("btn_berserker")
        self.gridLayout.addWidget(self.btn_berserker, 2, 3, 1, 1)
        self.btn_saber = QtWidgets.QPushButton(self.groupBox)
        self.btn_saber.setObjectName("btn_saber")
        self.gridLayout.addWidget(self.btn_saber, 1, 1, 1, 1)
        self.btn_5stars = QtWidgets.QPushButton(self.groupBox)
        self.btn_5stars.setObjectName("btn_5stars")
        self.gridLayout.addWidget(self.btn_5stars, 1, 0, 1, 1)
        self.btn_rider = QtWidgets.QPushButton(self.groupBox)
        self.btn_rider.setObjectName("btn_rider")
        self.gridLayout.addWidget(self.btn_rider, 1, 4, 1, 1)
        self.btn_assassin = QtWidgets.QPushButton(self.groupBox)
        self.btn_assassin.setObjectName("btn_assassin")
        self.gridLayout.addWidget(self.btn_assassin, 2, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 587, 581))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_servant_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_18.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_18.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_18.setText("")
        self.btn_servant_18.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_18.setObjectName("btn_servant_18")
        self.gridLayout_2.addWidget(self.btn_servant_18, 3, 2, 1, 1)
        self.btn_servant_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_5.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_5.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_5.setText("")
        self.btn_servant_5.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_5.setObjectName("btn_servant_5")
        self.gridLayout_2.addWidget(self.btn_servant_5, 0, 4, 1, 1)
        self.btn_servant_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_12.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_12.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_12.setText("")
        self.btn_servant_12.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_12.setObjectName("btn_servant_12")
        self.gridLayout_2.addWidget(self.btn_servant_12, 2, 1, 1, 1)
        self.btn_servant_20 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_20.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_20.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_20.setText("")
        self.btn_servant_20.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_20.setObjectName("btn_servant_20")
        self.gridLayout_2.addWidget(self.btn_servant_20, 3, 4, 1, 1)
        self.btn_servant_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_4.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_4.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_4.setText("")
        self.btn_servant_4.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_4.setObjectName("btn_servant_4")
        self.gridLayout_2.addWidget(self.btn_servant_4, 0, 3, 1, 1)
        self.btn_servant_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_16.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_16.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_16.setText("")
        self.btn_servant_16.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_16.setObjectName("btn_servant_16")
        self.gridLayout_2.addWidget(self.btn_servant_16, 3, 0, 1, 1)
        self.btn_servant_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_7.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_7.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_7.setText("")
        self.btn_servant_7.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_7.setObjectName("btn_servant_7")
        self.gridLayout_2.addWidget(self.btn_servant_7, 1, 1, 1, 1)
        self.btn_servant_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_13.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_13.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_13.setText("")
        self.btn_servant_13.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_13.setObjectName("btn_servant_13")
        self.gridLayout_2.addWidget(self.btn_servant_13, 2, 2, 1, 1)
        self.btn_servant_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_11.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_11.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_11.setText("")
        self.btn_servant_11.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_11.setObjectName("btn_servant_11")
        self.gridLayout_2.addWidget(self.btn_servant_11, 2, 0, 1, 1)
        self.btn_servant_22 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_22.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_22.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_22.setText("")
        self.btn_servant_22.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_22.setObjectName("btn_servant_22")
        self.gridLayout_2.addWidget(self.btn_servant_22, 4, 1, 1, 1)
        self.btn_servant_19 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_19.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_19.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_19.setText("")
        self.btn_servant_19.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_19.setObjectName("btn_servant_19")
        self.gridLayout_2.addWidget(self.btn_servant_19, 3, 3, 1, 1)
        self.btn_servant_23 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_23.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_23.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_23.setText("")
        self.btn_servant_23.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_23.setObjectName("btn_servant_23")
        self.gridLayout_2.addWidget(self.btn_servant_23, 4, 2, 1, 1)
        self.btn_servant_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_1.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_1.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_1.setText("")
        self.btn_servant_1.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_1.setObjectName("btn_servant_1")
        self.gridLayout_2.addWidget(self.btn_servant_1, 0, 0, 1, 1)
        self.btn_servant_24 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_24.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_24.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_24.setText("")
        self.btn_servant_24.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_24.setObjectName("btn_servant_24")
        self.gridLayout_2.addWidget(self.btn_servant_24, 4, 3, 1, 1)
        self.btn_servant_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_6.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_6.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_6.setText("")
        self.btn_servant_6.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_6.setObjectName("btn_servant_6")
        self.gridLayout_2.addWidget(self.btn_servant_6, 1, 0, 1, 1)
        self.btn_servant_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_2.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_2.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_2.setText("")
        self.btn_servant_2.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_2.setObjectName("btn_servant_2")
        self.gridLayout_2.addWidget(self.btn_servant_2, 0, 1, 1, 1)
        self.btn_servant_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_8.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_8.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_8.setText("")
        self.btn_servant_8.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_8.setObjectName("btn_servant_8")
        self.gridLayout_2.addWidget(self.btn_servant_8, 1, 2, 1, 1)
        self.btn_servant_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_3.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_3.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_3.setText("")
        self.btn_servant_3.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_3.setObjectName("btn_servant_3")
        self.gridLayout_2.addWidget(self.btn_servant_3, 0, 2, 1, 1)
        self.btn_servant_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_10.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_10.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_10.setText("")
        self.btn_servant_10.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_10.setObjectName("btn_servant_10")
        self.gridLayout_2.addWidget(self.btn_servant_10, 1, 4, 1, 1)
        self.btn_servant_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_9.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_9.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_9.setText("")
        self.btn_servant_9.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_9.setObjectName("btn_servant_9")
        self.gridLayout_2.addWidget(self.btn_servant_9, 1, 3, 1, 1)
        self.btn_servant_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_14.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_14.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_14.setText("")
        self.btn_servant_14.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_14.setObjectName("btn_servant_14")
        self.gridLayout_2.addWidget(self.btn_servant_14, 2, 3, 1, 1)
        self.btn_servant_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_17.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_17.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_17.setText("")
        self.btn_servant_17.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_17.setObjectName("btn_servant_17")
        self.gridLayout_2.addWidget(self.btn_servant_17, 3, 1, 1, 1)
        self.btn_servant_25 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_25.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_25.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_25.setText("")
        self.btn_servant_25.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_25.setObjectName("btn_servant_25")
        self.gridLayout_2.addWidget(self.btn_servant_25, 4, 4, 1, 1)
        self.btn_servant_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_15.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_15.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_15.setText("")
        self.btn_servant_15.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_15.setObjectName("btn_servant_15")
        self.gridLayout_2.addWidget(self.btn_servant_15, 2, 4, 1, 1)
        self.btn_servant_21 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_21.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_21.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_21.setText("")
        self.btn_servant_21.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_21.setObjectName("btn_servant_21")
        self.gridLayout_2.addWidget(self.btn_servant_21, 4, 0, 1, 1)
        self.btn_servant_26 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_26.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_26.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_26.setText("")
        self.btn_servant_26.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_26.setObjectName("btn_servant_26")
        self.gridLayout_2.addWidget(self.btn_servant_26, 5, 0, 1, 1)
        self.btn_servant_27 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_27.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_27.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_27.setText("")
        self.btn_servant_27.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_27.setObjectName("btn_servant_27")
        self.gridLayout_2.addWidget(self.btn_servant_27, 5, 1, 1, 1)
        self.btn_servant_28 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_28.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_28.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_28.setText("")
        self.btn_servant_28.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_28.setObjectName("btn_servant_28")
        self.gridLayout_2.addWidget(self.btn_servant_28, 5, 2, 1, 1)
        self.btn_servant_29 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_29.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_29.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_29.setText("")
        self.btn_servant_29.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_29.setObjectName("btn_servant_29")
        self.gridLayout_2.addWidget(self.btn_servant_29, 5, 3, 1, 1)
        self.btn_servant_30 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.btn_servant_30.setMinimumSize(QtCore.QSize(80, 87))
        self.btn_servant_30.setMaximumSize(QtCore.QSize(80, 87))
        self.btn_servant_30.setText("")
        self.btn_servant_30.setIconSize(QtCore.QSize(80, 87))
        self.btn_servant_30.setObjectName("btn_servant_30")
        self.gridLayout_2.addWidget(self.btn_servant_30, 5, 4, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_10.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "选择从者"))
        self.groupBox_2.setTitle(_translate("Dialog", "设定数据"))
        self.btn_data_reset.setText(_translate("Dialog", "还原从者数据"))
        self.btn_data_input.setText(_translate("Dialog", "导入数据(待开发)"))
        self.btn_data_output.setText(_translate("Dialog", "保存从者数据"))
        self.label_servant_level.setText(_translate("Dialog", "等级"))
        self.label_servant_np.setText(_translate("Dialog", "宝具"))
        self.label_servant_fufu.setText(_translate("Dialog", "芙芙"))
        self.label_servant_skill1.setText(_translate("Dialog", "1技能"))
        self.label_servant_skill2.setText(_translate("Dialog", "2技能"))
        self.label_servant_skill3.setText(_translate("Dialog", "3技能"))
        self.btn_clear.setText(_translate("Dialog", "清  空"))
        self.btn_confirm.setText(_translate("Dialog", "确  认"))
        self.btn_cancel.setText(_translate("Dialog", "取  消"))
        self.groupBox.setTitle(_translate("Dialog", "从者列表"))
        self.btn_kongming.setText(_translate("Dialog", "诸葛孔明"))
        self.btn_merlin.setText(_translate("Dialog", "梅  林"))
        self.btn_cba.setText(_translate("Dialog", "斯卡哈·斯卡蒂"))
        self.btn_tamamo.setText(_translate("Dialog", "玉藻前"))
        self.btn_nero_bride.setText(_translate("Dialog", "花嫁尼禄"))
        self.btn_lancer.setText(_translate("Dialog", "Lancer"))
        self.btn_lowstars.setText(_translate("Dialog", "低 星"))
        self.btn_4stars.setText(_translate("Dialog", "4 星"))
        self.btn_caster.setText(_translate("Dialog", "Caster"))
        self.btn_archer.setText(_translate("Dialog", "Archer"))
        self.btn_extra.setText(_translate("Dialog", "Extra"))
        self.btn_berserker.setText(_translate("Dialog", "Berserker"))
        self.btn_saber.setText(_translate("Dialog", "Saber"))
        self.btn_5stars.setText(_translate("Dialog", "5 星"))
        self.btn_rider.setText(_translate("Dialog", "Rider"))
        self.btn_assassin.setText(_translate("Dialog", "Assassin"))
