# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ViewDetailsUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(475, 594)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_pic = QtWidgets.QLabel(Dialog)
        self.label_pic.setMinimumSize(QtCore.QSize(110, 120))
        self.label_pic.setMaximumSize(QtCore.QSize(110, 120))
        self.label_pic.setText("")
        self.label_pic.setObjectName("label_pic")
        self.horizontalLayout.addWidget(self.label_pic)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.label_details = QtWidgets.QLabel(Dialog)
        self.label_details.setText("")
        self.label_details.setObjectName("label_details")
        self.horizontalLayout.addWidget(self.label_details)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_attribute = QtWidgets.QLabel(Dialog)
        self.label_attribute.setText("")
        self.label_attribute.setObjectName("label_attribute")
        self.verticalLayout.addWidget(self.label_attribute)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_state = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_state.sizePolicy().hasHeightForWidth())
        self.label_state.setSizePolicy(sizePolicy)
        self.label_state.setText("")
        self.label_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state.setObjectName("label_state")
        self.horizontalLayout_2.addWidget(self.label_state)
        self.label_state_num = QtWidgets.QLabel(Dialog)
        self.label_state_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_num.setObjectName("label_state_num")
        self.horizontalLayout_2.addWidget(self.label_state_num)
        self.label_state_times = QtWidgets.QLabel(Dialog)
        self.label_state_times.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_times.setObjectName("label_state_times")
        self.horizontalLayout_2.addWidget(self.label_state_times)
        self.label_state_round = QtWidgets.QLabel(Dialog)
        self.label_state_round.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_round.setObjectName("label_state_round")
        self.horizontalLayout_2.addWidget(self.label_state_round)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "详细信息"))
        self.label.setText(_translate("Dialog", "特性:"))
        self.label_6.setText(_translate("Dialog", "状态列表:"))
        self.label_state_num.setText(_translate("Dialog", "TextLabel"))
        self.label_state_times.setText(_translate("Dialog", "TextLabel"))
        self.label_state_round.setText(_translate("Dialog", "TextLabel"))
